// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Msg_Move.proto

#ifndef PROTOBUF_Msg_5fMove_2eproto__INCLUDED
#define PROTOBUF_Msg_5fMove_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
class ActionNtyItem;
class ActionNtyItemDefaultTypeInternal;
extern ActionNtyItemDefaultTypeInternal _ActionNtyItem_default_instance_;
class ActionReqItem;
class ActionReqItemDefaultTypeInternal;
extern ActionReqItemDefaultTypeInternal _ActionReqItem_default_instance_;
class HeartBeatAck;
class HeartBeatAckDefaultTypeInternal;
extern HeartBeatAckDefaultTypeInternal _HeartBeatAck_default_instance_;
class HeartBeatReq;
class HeartBeatReqDefaultTypeInternal;
extern HeartBeatReqDefaultTypeInternal _HeartBeatReq_default_instance_;
class NewItem;
class NewItemDefaultTypeInternal;
extern NewItemDefaultTypeInternal _NewItem_default_instance_;
class ObjectActionNty;
class ObjectActionNtyDefaultTypeInternal;
extern ObjectActionNtyDefaultTypeInternal _ObjectActionNty_default_instance_;
class ObjectActionReq;
class ObjectActionReqDefaultTypeInternal;
extern ObjectActionReqDefaultTypeInternal _ObjectActionReq_default_instance_;
class ObjectDieNotify;
class ObjectDieNotifyDefaultTypeInternal;
extern ObjectDieNotifyDefaultTypeInternal _ObjectDieNotify_default_instance_;
class ObjectNewNty;
class ObjectNewNtyDefaultTypeInternal;
extern ObjectNewNtyDefaultTypeInternal _ObjectNewNty_default_instance_;
class ObjectRemoveNty;
class ObjectRemoveNtyDefaultTypeInternal;
extern ObjectRemoveNtyDefaultTypeInternal _ObjectRemoveNty_default_instance_;
class ObjectValueChange;
class ObjectValueChangeDefaultTypeInternal;
extern ObjectValueChangeDefaultTypeInternal _ObjectValueChange_default_instance_;
class ObjectValueChangeNtf;
class ObjectValueChangeNtfDefaultTypeInternal;
extern ObjectValueChangeNtfDefaultTypeInternal _ObjectValueChangeNtf_default_instance_;

namespace protobuf_Msg_5fMove_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_Msg_5fMove_2eproto

// ===================================================================

class ActionNtyItem : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ActionNtyItem) */ {
 public:
  ActionNtyItem();
  virtual ~ActionNtyItem();

  ActionNtyItem(const ActionNtyItem& from);

  inline ActionNtyItem& operator=(const ActionNtyItem& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ActionNtyItem& default_instance();

  static inline const ActionNtyItem* internal_default_instance() {
    return reinterpret_cast<const ActionNtyItem*>(
               &_ActionNtyItem_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(ActionNtyItem* other);

  // implements Message ----------------------------------------------

  inline ActionNtyItem* New() const PROTOBUF_FINAL { return New(NULL); }

  ActionNtyItem* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ActionNtyItem& from);
  void MergeFrom(const ActionNtyItem& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ActionNtyItem* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 ObjectGuid = 1;
  void clear_objectguid();
  static const int kObjectGuidFieldNumber = 1;
  ::google::protobuf::uint64 objectguid() const;
  void set_objectguid(::google::protobuf::uint64 value);

  // int32 ObjStatue = 2;
  void clear_objstatue();
  static const int kObjStatueFieldNumber = 2;
  ::google::protobuf::int32 objstatue() const;
  void set_objstatue(::google::protobuf::int32 value);

  // int32 ActorID = 3;
  void clear_actorid();
  static const int kActorIDFieldNumber = 3;
  ::google::protobuf::int32 actorid() const;
  void set_actorid(::google::protobuf::int32 value);

  // uint64 ControlerID = 4;
  void clear_controlerid();
  static const int kControlerIDFieldNumber = 4;
  ::google::protobuf::uint64 controlerid() const;
  void set_controlerid(::google::protobuf::uint64 value);

  // int32 ActionID = 5;
  void clear_actionid();
  static const int kActionIDFieldNumber = 5;
  ::google::protobuf::int32 actionid() const;
  void set_actionid(::google::protobuf::int32 value);

  // int32 ActionTime = 6;
  void clear_actiontime();
  static const int kActionTimeFieldNumber = 6;
  ::google::protobuf::int32 actiontime() const;
  void set_actiontime(::google::protobuf::int32 value);

  // int32 BuffStatue = 7;
  void clear_buffstatue();
  static const int kBuffStatueFieldNumber = 7;
  ::google::protobuf::int32 buffstatue() const;
  void set_buffstatue(::google::protobuf::int32 value);

  // float X = 8;
  void clear_x();
  static const int kXFieldNumber = 8;
  float x() const;
  void set_x(float value);

  // float Y = 9;
  void clear_y();
  static const int kYFieldNumber = 9;
  float y() const;
  void set_y(float value);

  // float Z = 10;
  void clear_z();
  static const int kZFieldNumber = 10;
  float z() const;
  void set_z(float value);

  // float Ft = 11;
  void clear_ft();
  static const int kFtFieldNumber = 11;
  float ft() const;
  void set_ft(float value);

  // int32 Hp = 12;
  void clear_hp();
  static const int kHpFieldNumber = 12;
  ::google::protobuf::int32 hp() const;
  void set_hp(::google::protobuf::int32 value);

  // int32 Mp = 13;
  void clear_mp();
  static const int kMpFieldNumber = 13;
  ::google::protobuf::int32 mp() const;
  void set_mp(::google::protobuf::int32 value);

  // int32 HpMax = 14;
  void clear_hpmax();
  static const int kHpMaxFieldNumber = 14;
  ::google::protobuf::int32 hpmax() const;
  void set_hpmax(::google::protobuf::int32 value);

  // int32 MpMax = 15;
  void clear_mpmax();
  static const int kMpMaxFieldNumber = 15;
  ::google::protobuf::int32 mpmax() const;
  void set_mpmax(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ActionNtyItem)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint64 objectguid_;
  ::google::protobuf::int32 objstatue_;
  ::google::protobuf::int32 actorid_;
  ::google::protobuf::uint64 controlerid_;
  ::google::protobuf::int32 actionid_;
  ::google::protobuf::int32 actiontime_;
  ::google::protobuf::int32 buffstatue_;
  float x_;
  float y_;
  float z_;
  float ft_;
  ::google::protobuf::int32 hp_;
  ::google::protobuf::int32 mp_;
  ::google::protobuf::int32 hpmax_;
  ::google::protobuf::int32 mpmax_;
  mutable int _cached_size_;
  friend struct protobuf_Msg_5fMove_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ActionReqItem : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ActionReqItem) */ {
 public:
  ActionReqItem();
  virtual ~ActionReqItem();

  ActionReqItem(const ActionReqItem& from);

  inline ActionReqItem& operator=(const ActionReqItem& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ActionReqItem& default_instance();

  static inline const ActionReqItem* internal_default_instance() {
    return reinterpret_cast<const ActionReqItem*>(
               &_ActionReqItem_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(ActionReqItem* other);

  // implements Message ----------------------------------------------

  inline ActionReqItem* New() const PROTOBUF_FINAL { return New(NULL); }

  ActionReqItem* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ActionReqItem& from);
  void MergeFrom(const ActionReqItem& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ActionReqItem* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated uint64 TargetObjects = 12;
  int targetobjects_size() const;
  void clear_targetobjects();
  static const int kTargetObjectsFieldNumber = 12;
  ::google::protobuf::uint64 targetobjects(int index) const;
  void set_targetobjects(int index, ::google::protobuf::uint64 value);
  void add_targetobjects(::google::protobuf::uint64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
      targetobjects() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
      mutable_targetobjects();

  // uint64 ObjectGuid = 1;
  void clear_objectguid();
  static const int kObjectGuidFieldNumber = 1;
  ::google::protobuf::uint64 objectguid() const;
  void set_objectguid(::google::protobuf::uint64 value);

  // int32 ActionID = 2;
  void clear_actionid();
  static const int kActionIDFieldNumber = 2;
  ::google::protobuf::int32 actionid() const;
  void set_actionid(::google::protobuf::int32 value);

  // int32 IsSkill = 3;
  void clear_isskill();
  static const int kIsSkillFieldNumber = 3;
  ::google::protobuf::int32 isskill() const;
  void set_isskill(::google::protobuf::int32 value);

  // float HostX = 4;
  void clear_hostx();
  static const int kHostXFieldNumber = 4;
  float hostx() const;
  void set_hostx(float value);

  // float HostY = 5;
  void clear_hosty();
  static const int kHostYFieldNumber = 5;
  float hosty() const;
  void set_hosty(float value);

  // float HostZ = 6;
  void clear_hostz();
  static const int kHostZFieldNumber = 6;
  float hostz() const;
  void set_hostz(float value);

  // float HostFt = 7;
  void clear_hostft();
  static const int kHostFtFieldNumber = 7;
  float hostft() const;
  void set_hostft(float value);

  // float TargetX = 8;
  void clear_targetx();
  static const int kTargetXFieldNumber = 8;
  float targetx() const;
  void set_targetx(float value);

  // float TargetY = 9;
  void clear_targety();
  static const int kTargetYFieldNumber = 9;
  float targety() const;
  void set_targety(float value);

  // float TargetZ = 10;
  void clear_targetz();
  static const int kTargetZFieldNumber = 10;
  float targetz() const;
  void set_targetz(float value);

  // float TargetFt = 11;
  void clear_targetft();
  static const int kTargetFtFieldNumber = 11;
  float targetft() const;
  void set_targetft(float value);

  // @@protoc_insertion_point(class_scope:ActionReqItem)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 > targetobjects_;
  mutable int _targetobjects_cached_byte_size_;
  ::google::protobuf::uint64 objectguid_;
  ::google::protobuf::int32 actionid_;
  ::google::protobuf::int32 isskill_;
  float hostx_;
  float hosty_;
  float hostz_;
  float hostft_;
  float targetx_;
  float targety_;
  float targetz_;
  float targetft_;
  mutable int _cached_size_;
  friend struct protobuf_Msg_5fMove_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ObjectActionReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ObjectActionReq) */ {
 public:
  ObjectActionReq();
  virtual ~ObjectActionReq();

  ObjectActionReq(const ObjectActionReq& from);

  inline ObjectActionReq& operator=(const ObjectActionReq& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ObjectActionReq& default_instance();

  static inline const ObjectActionReq* internal_default_instance() {
    return reinterpret_cast<const ObjectActionReq*>(
               &_ObjectActionReq_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(ObjectActionReq* other);

  // implements Message ----------------------------------------------

  inline ObjectActionReq* New() const PROTOBUF_FINAL { return New(NULL); }

  ObjectActionReq* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ObjectActionReq& from);
  void MergeFrom(const ObjectActionReq& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ObjectActionReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .ActionReqItem ActionList = 1;
  int actionlist_size() const;
  void clear_actionlist();
  static const int kActionListFieldNumber = 1;
  const ::ActionReqItem& actionlist(int index) const;
  ::ActionReqItem* mutable_actionlist(int index);
  ::ActionReqItem* add_actionlist();
  ::google::protobuf::RepeatedPtrField< ::ActionReqItem >*
      mutable_actionlist();
  const ::google::protobuf::RepeatedPtrField< ::ActionReqItem >&
      actionlist() const;

  // @@protoc_insertion_point(class_scope:ObjectActionReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::ActionReqItem > actionlist_;
  mutable int _cached_size_;
  friend struct protobuf_Msg_5fMove_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ObjectActionNty : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ObjectActionNty) */ {
 public:
  ObjectActionNty();
  virtual ~ObjectActionNty();

  ObjectActionNty(const ObjectActionNty& from);

  inline ObjectActionNty& operator=(const ObjectActionNty& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ObjectActionNty& default_instance();

  static inline const ObjectActionNty* internal_default_instance() {
    return reinterpret_cast<const ObjectActionNty*>(
               &_ObjectActionNty_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(ObjectActionNty* other);

  // implements Message ----------------------------------------------

  inline ObjectActionNty* New() const PROTOBUF_FINAL { return New(NULL); }

  ObjectActionNty* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ObjectActionNty& from);
  void MergeFrom(const ObjectActionNty& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ObjectActionNty* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .ActionNtyItem ActionList = 1;
  int actionlist_size() const;
  void clear_actionlist();
  static const int kActionListFieldNumber = 1;
  const ::ActionNtyItem& actionlist(int index) const;
  ::ActionNtyItem* mutable_actionlist(int index);
  ::ActionNtyItem* add_actionlist();
  ::google::protobuf::RepeatedPtrField< ::ActionNtyItem >*
      mutable_actionlist();
  const ::google::protobuf::RepeatedPtrField< ::ActionNtyItem >&
      actionlist() const;

  // @@protoc_insertion_point(class_scope:ObjectActionNty)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::ActionNtyItem > actionlist_;
  mutable int _cached_size_;
  friend struct protobuf_Msg_5fMove_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class NewItem : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:NewItem) */ {
 public:
  NewItem();
  virtual ~NewItem();

  NewItem(const NewItem& from);

  inline NewItem& operator=(const NewItem& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const NewItem& default_instance();

  static inline const NewItem* internal_default_instance() {
    return reinterpret_cast<const NewItem*>(
               &_NewItem_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    4;

  void Swap(NewItem* other);

  // implements Message ----------------------------------------------

  inline NewItem* New() const PROTOBUF_FINAL { return New(NULL); }

  NewItem* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const NewItem& from);
  void MergeFrom(const NewItem& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(NewItem* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string Name = 5;
  void clear_name();
  static const int kNameFieldNumber = 5;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // uint64 ObjectGuid = 1;
  void clear_objectguid();
  static const int kObjectGuidFieldNumber = 1;
  ::google::protobuf::uint64 objectguid() const;
  void set_objectguid(::google::protobuf::uint64 value);

  // int32 ObjType = 2;
  void clear_objtype();
  static const int kObjTypeFieldNumber = 2;
  ::google::protobuf::int32 objtype() const;
  void set_objtype(::google::protobuf::int32 value);

  // int32 ObjStatue = 3;
  void clear_objstatue();
  static const int kObjStatueFieldNumber = 3;
  ::google::protobuf::int32 objstatue() const;
  void set_objstatue(::google::protobuf::int32 value);

  // int32 ActorID = 4;
  void clear_actorid();
  static const int kActorIDFieldNumber = 4;
  ::google::protobuf::int32 actorid() const;
  void set_actorid(::google::protobuf::int32 value);

  // int32 Level = 6;
  void clear_level();
  static const int kLevelFieldNumber = 6;
  ::google::protobuf::int32 level() const;
  void set_level(::google::protobuf::int32 value);

  // uint64 HostGuid = 7;
  void clear_hostguid();
  static const int kHostGuidFieldNumber = 7;
  ::google::protobuf::uint64 hostguid() const;
  void set_hostguid(::google::protobuf::uint64 value);

  // uint64 ControlerID = 8;
  void clear_controlerid();
  static const int kControlerIDFieldNumber = 8;
  ::google::protobuf::uint64 controlerid() const;
  void set_controlerid(::google::protobuf::uint64 value);

  // uint64 SummonID = 9;
  void clear_summonid();
  static const int kSummonIDFieldNumber = 9;
  ::google::protobuf::uint64 summonid() const;
  void set_summonid(::google::protobuf::uint64 value);

  // float X = 10;
  void clear_x();
  static const int kXFieldNumber = 10;
  float x() const;
  void set_x(float value);

  // float Y = 11;
  void clear_y();
  static const int kYFieldNumber = 11;
  float y() const;
  void set_y(float value);

  // float Z = 12;
  void clear_z();
  static const int kZFieldNumber = 12;
  float z() const;
  void set_z(float value);

  // float Ft = 13;
  void clear_ft();
  static const int kFtFieldNumber = 13;
  float ft() const;
  void set_ft(float value);

  // int32 Hp = 14;
  void clear_hp();
  static const int kHpFieldNumber = 14;
  ::google::protobuf::int32 hp() const;
  void set_hp(::google::protobuf::int32 value);

  // int32 Mp = 15;
  void clear_mp();
  static const int kMpFieldNumber = 15;
  ::google::protobuf::int32 mp() const;
  void set_mp(::google::protobuf::int32 value);

  // int32 HpMax = 16;
  void clear_hpmax();
  static const int kHpMaxFieldNumber = 16;
  ::google::protobuf::int32 hpmax() const;
  void set_hpmax(::google::protobuf::int32 value);

  // int32 MpMax = 17;
  void clear_mpmax();
  static const int kMpMaxFieldNumber = 17;
  ::google::protobuf::int32 mpmax() const;
  void set_mpmax(::google::protobuf::int32 value);

  // int32 Weapon = 18;
  void clear_weapon();
  static const int kWeaponFieldNumber = 18;
  ::google::protobuf::int32 weapon() const;
  void set_weapon(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:NewItem)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::uint64 objectguid_;
  ::google::protobuf::int32 objtype_;
  ::google::protobuf::int32 objstatue_;
  ::google::protobuf::int32 actorid_;
  ::google::protobuf::int32 level_;
  ::google::protobuf::uint64 hostguid_;
  ::google::protobuf::uint64 controlerid_;
  ::google::protobuf::uint64 summonid_;
  float x_;
  float y_;
  float z_;
  float ft_;
  ::google::protobuf::int32 hp_;
  ::google::protobuf::int32 mp_;
  ::google::protobuf::int32 hpmax_;
  ::google::protobuf::int32 mpmax_;
  ::google::protobuf::int32 weapon_;
  mutable int _cached_size_;
  friend struct protobuf_Msg_5fMove_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ObjectNewNty : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ObjectNewNty) */ {
 public:
  ObjectNewNty();
  virtual ~ObjectNewNty();

  ObjectNewNty(const ObjectNewNty& from);

  inline ObjectNewNty& operator=(const ObjectNewNty& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ObjectNewNty& default_instance();

  static inline const ObjectNewNty* internal_default_instance() {
    return reinterpret_cast<const ObjectNewNty*>(
               &_ObjectNewNty_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    5;

  void Swap(ObjectNewNty* other);

  // implements Message ----------------------------------------------

  inline ObjectNewNty* New() const PROTOBUF_FINAL { return New(NULL); }

  ObjectNewNty* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ObjectNewNty& from);
  void MergeFrom(const ObjectNewNty& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ObjectNewNty* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .NewItem NewList = 1;
  int newlist_size() const;
  void clear_newlist();
  static const int kNewListFieldNumber = 1;
  const ::NewItem& newlist(int index) const;
  ::NewItem* mutable_newlist(int index);
  ::NewItem* add_newlist();
  ::google::protobuf::RepeatedPtrField< ::NewItem >*
      mutable_newlist();
  const ::google::protobuf::RepeatedPtrField< ::NewItem >&
      newlist() const;

  // @@protoc_insertion_point(class_scope:ObjectNewNty)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::NewItem > newlist_;
  mutable int _cached_size_;
  friend struct protobuf_Msg_5fMove_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ObjectRemoveNty : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ObjectRemoveNty) */ {
 public:
  ObjectRemoveNty();
  virtual ~ObjectRemoveNty();

  ObjectRemoveNty(const ObjectRemoveNty& from);

  inline ObjectRemoveNty& operator=(const ObjectRemoveNty& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ObjectRemoveNty& default_instance();

  static inline const ObjectRemoveNty* internal_default_instance() {
    return reinterpret_cast<const ObjectRemoveNty*>(
               &_ObjectRemoveNty_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    6;

  void Swap(ObjectRemoveNty* other);

  // implements Message ----------------------------------------------

  inline ObjectRemoveNty* New() const PROTOBUF_FINAL { return New(NULL); }

  ObjectRemoveNty* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ObjectRemoveNty& from);
  void MergeFrom(const ObjectRemoveNty& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ObjectRemoveNty* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated uint64 RemoveList = 1;
  int removelist_size() const;
  void clear_removelist();
  static const int kRemoveListFieldNumber = 1;
  ::google::protobuf::uint64 removelist(int index) const;
  void set_removelist(int index, ::google::protobuf::uint64 value);
  void add_removelist(::google::protobuf::uint64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
      removelist() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
      mutable_removelist();

  // @@protoc_insertion_point(class_scope:ObjectRemoveNty)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 > removelist_;
  mutable int _removelist_cached_byte_size_;
  mutable int _cached_size_;
  friend struct protobuf_Msg_5fMove_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class HeartBeatReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:HeartBeatReq) */ {
 public:
  HeartBeatReq();
  virtual ~HeartBeatReq();

  HeartBeatReq(const HeartBeatReq& from);

  inline HeartBeatReq& operator=(const HeartBeatReq& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const HeartBeatReq& default_instance();

  static inline const HeartBeatReq* internal_default_instance() {
    return reinterpret_cast<const HeartBeatReq*>(
               &_HeartBeatReq_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    7;

  void Swap(HeartBeatReq* other);

  // implements Message ----------------------------------------------

  inline HeartBeatReq* New() const PROTOBUF_FINAL { return New(NULL); }

  HeartBeatReq* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const HeartBeatReq& from);
  void MergeFrom(const HeartBeatReq& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(HeartBeatReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 TimeStamp = 1;
  void clear_timestamp();
  static const int kTimeStampFieldNumber = 1;
  ::google::protobuf::uint32 timestamp() const;
  void set_timestamp(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:HeartBeatReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 timestamp_;
  mutable int _cached_size_;
  friend struct protobuf_Msg_5fMove_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class HeartBeatAck : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:HeartBeatAck) */ {
 public:
  HeartBeatAck();
  virtual ~HeartBeatAck();

  HeartBeatAck(const HeartBeatAck& from);

  inline HeartBeatAck& operator=(const HeartBeatAck& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const HeartBeatAck& default_instance();

  static inline const HeartBeatAck* internal_default_instance() {
    return reinterpret_cast<const HeartBeatAck*>(
               &_HeartBeatAck_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    8;

  void Swap(HeartBeatAck* other);

  // implements Message ----------------------------------------------

  inline HeartBeatAck* New() const PROTOBUF_FINAL { return New(NULL); }

  HeartBeatAck* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const HeartBeatAck& from);
  void MergeFrom(const HeartBeatAck& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(HeartBeatAck* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 TimeStamp = 1;
  void clear_timestamp();
  static const int kTimeStampFieldNumber = 1;
  ::google::protobuf::uint32 timestamp() const;
  void set_timestamp(::google::protobuf::uint32 value);

  // uint32 ServerTime = 2;
  void clear_servertime();
  static const int kServerTimeFieldNumber = 2;
  ::google::protobuf::uint32 servertime() const;
  void set_servertime(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:HeartBeatAck)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 timestamp_;
  ::google::protobuf::uint32 servertime_;
  mutable int _cached_size_;
  friend struct protobuf_Msg_5fMove_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ObjectDieNotify : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ObjectDieNotify) */ {
 public:
  ObjectDieNotify();
  virtual ~ObjectDieNotify();

  ObjectDieNotify(const ObjectDieNotify& from);

  inline ObjectDieNotify& operator=(const ObjectDieNotify& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ObjectDieNotify& default_instance();

  static inline const ObjectDieNotify* internal_default_instance() {
    return reinterpret_cast<const ObjectDieNotify*>(
               &_ObjectDieNotify_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    9;

  void Swap(ObjectDieNotify* other);

  // implements Message ----------------------------------------------

  inline ObjectDieNotify* New() const PROTOBUF_FINAL { return New(NULL); }

  ObjectDieNotify* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ObjectDieNotify& from);
  void MergeFrom(const ObjectDieNotify& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ObjectDieNotify* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 ObjectGuid = 1;
  void clear_objectguid();
  static const int kObjectGuidFieldNumber = 1;
  ::google::protobuf::uint64 objectguid() const;
  void set_objectguid(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:ObjectDieNotify)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint64 objectguid_;
  mutable int _cached_size_;
  friend struct protobuf_Msg_5fMove_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ObjectValueChange : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ObjectValueChange) */ {
 public:
  ObjectValueChange();
  virtual ~ObjectValueChange();

  ObjectValueChange(const ObjectValueChange& from);

  inline ObjectValueChange& operator=(const ObjectValueChange& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ObjectValueChange& default_instance();

  static inline const ObjectValueChange* internal_default_instance() {
    return reinterpret_cast<const ObjectValueChange*>(
               &_ObjectValueChange_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    10;

  void Swap(ObjectValueChange* other);

  // implements Message ----------------------------------------------

  inline ObjectValueChange* New() const PROTOBUF_FINAL { return New(NULL); }

  ObjectValueChange* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ObjectValueChange& from);
  void MergeFrom(const ObjectValueChange& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ObjectValueChange* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 TargetGUID = 1;
  void clear_targetguid();
  static const int kTargetGUIDFieldNumber = 1;
  ::google::protobuf::uint64 targetguid() const;
  void set_targetguid(::google::protobuf::uint64 value);

  // int32 ValueID = 2;
  void clear_valueid();
  static const int kValueIDFieldNumber = 2;
  ::google::protobuf::int32 valueid() const;
  void set_valueid(::google::protobuf::int32 value);

  // int32 Value = 3;
  void clear_value();
  static const int kValueFieldNumber = 3;
  ::google::protobuf::int32 value() const;
  void set_value(::google::protobuf::int32 value);

  // bool Crit = 4;
  void clear_crit();
  static const int kCritFieldNumber = 4;
  bool crit() const;
  void set_crit(bool value);

  // @@protoc_insertion_point(class_scope:ObjectValueChange)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint64 targetguid_;
  ::google::protobuf::int32 valueid_;
  ::google::protobuf::int32 value_;
  bool crit_;
  mutable int _cached_size_;
  friend struct protobuf_Msg_5fMove_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ObjectValueChangeNtf : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ObjectValueChangeNtf) */ {
 public:
  ObjectValueChangeNtf();
  virtual ~ObjectValueChangeNtf();

  ObjectValueChangeNtf(const ObjectValueChangeNtf& from);

  inline ObjectValueChangeNtf& operator=(const ObjectValueChangeNtf& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ObjectValueChangeNtf& default_instance();

  static inline const ObjectValueChangeNtf* internal_default_instance() {
    return reinterpret_cast<const ObjectValueChangeNtf*>(
               &_ObjectValueChangeNtf_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    11;

  void Swap(ObjectValueChangeNtf* other);

  // implements Message ----------------------------------------------

  inline ObjectValueChangeNtf* New() const PROTOBUF_FINAL { return New(NULL); }

  ObjectValueChangeNtf* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ObjectValueChangeNtf& from);
  void MergeFrom(const ObjectValueChangeNtf& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ObjectValueChangeNtf* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .ObjectValueChange ChangeList = 1;
  int changelist_size() const;
  void clear_changelist();
  static const int kChangeListFieldNumber = 1;
  const ::ObjectValueChange& changelist(int index) const;
  ::ObjectValueChange* mutable_changelist(int index);
  ::ObjectValueChange* add_changelist();
  ::google::protobuf::RepeatedPtrField< ::ObjectValueChange >*
      mutable_changelist();
  const ::google::protobuf::RepeatedPtrField< ::ObjectValueChange >&
      changelist() const;

  // @@protoc_insertion_point(class_scope:ObjectValueChangeNtf)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::ObjectValueChange > changelist_;
  mutable int _cached_size_;
  friend struct protobuf_Msg_5fMove_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// ActionNtyItem

// uint64 ObjectGuid = 1;
inline void ActionNtyItem::clear_objectguid() {
  objectguid_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 ActionNtyItem::objectguid() const {
  // @@protoc_insertion_point(field_get:ActionNtyItem.ObjectGuid)
  return objectguid_;
}
inline void ActionNtyItem::set_objectguid(::google::protobuf::uint64 value) {
  
  objectguid_ = value;
  // @@protoc_insertion_point(field_set:ActionNtyItem.ObjectGuid)
}

// int32 ObjStatue = 2;
inline void ActionNtyItem::clear_objstatue() {
  objstatue_ = 0;
}
inline ::google::protobuf::int32 ActionNtyItem::objstatue() const {
  // @@protoc_insertion_point(field_get:ActionNtyItem.ObjStatue)
  return objstatue_;
}
inline void ActionNtyItem::set_objstatue(::google::protobuf::int32 value) {
  
  objstatue_ = value;
  // @@protoc_insertion_point(field_set:ActionNtyItem.ObjStatue)
}

// int32 ActorID = 3;
inline void ActionNtyItem::clear_actorid() {
  actorid_ = 0;
}
inline ::google::protobuf::int32 ActionNtyItem::actorid() const {
  // @@protoc_insertion_point(field_get:ActionNtyItem.ActorID)
  return actorid_;
}
inline void ActionNtyItem::set_actorid(::google::protobuf::int32 value) {
  
  actorid_ = value;
  // @@protoc_insertion_point(field_set:ActionNtyItem.ActorID)
}

// uint64 ControlerID = 4;
inline void ActionNtyItem::clear_controlerid() {
  controlerid_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 ActionNtyItem::controlerid() const {
  // @@protoc_insertion_point(field_get:ActionNtyItem.ControlerID)
  return controlerid_;
}
inline void ActionNtyItem::set_controlerid(::google::protobuf::uint64 value) {
  
  controlerid_ = value;
  // @@protoc_insertion_point(field_set:ActionNtyItem.ControlerID)
}

// int32 ActionID = 5;
inline void ActionNtyItem::clear_actionid() {
  actionid_ = 0;
}
inline ::google::protobuf::int32 ActionNtyItem::actionid() const {
  // @@protoc_insertion_point(field_get:ActionNtyItem.ActionID)
  return actionid_;
}
inline void ActionNtyItem::set_actionid(::google::protobuf::int32 value) {
  
  actionid_ = value;
  // @@protoc_insertion_point(field_set:ActionNtyItem.ActionID)
}

// int32 ActionTime = 6;
inline void ActionNtyItem::clear_actiontime() {
  actiontime_ = 0;
}
inline ::google::protobuf::int32 ActionNtyItem::actiontime() const {
  // @@protoc_insertion_point(field_get:ActionNtyItem.ActionTime)
  return actiontime_;
}
inline void ActionNtyItem::set_actiontime(::google::protobuf::int32 value) {
  
  actiontime_ = value;
  // @@protoc_insertion_point(field_set:ActionNtyItem.ActionTime)
}

// int32 BuffStatue = 7;
inline void ActionNtyItem::clear_buffstatue() {
  buffstatue_ = 0;
}
inline ::google::protobuf::int32 ActionNtyItem::buffstatue() const {
  // @@protoc_insertion_point(field_get:ActionNtyItem.BuffStatue)
  return buffstatue_;
}
inline void ActionNtyItem::set_buffstatue(::google::protobuf::int32 value) {
  
  buffstatue_ = value;
  // @@protoc_insertion_point(field_set:ActionNtyItem.BuffStatue)
}

// float X = 8;
inline void ActionNtyItem::clear_x() {
  x_ = 0;
}
inline float ActionNtyItem::x() const {
  // @@protoc_insertion_point(field_get:ActionNtyItem.X)
  return x_;
}
inline void ActionNtyItem::set_x(float value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:ActionNtyItem.X)
}

// float Y = 9;
inline void ActionNtyItem::clear_y() {
  y_ = 0;
}
inline float ActionNtyItem::y() const {
  // @@protoc_insertion_point(field_get:ActionNtyItem.Y)
  return y_;
}
inline void ActionNtyItem::set_y(float value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:ActionNtyItem.Y)
}

// float Z = 10;
inline void ActionNtyItem::clear_z() {
  z_ = 0;
}
inline float ActionNtyItem::z() const {
  // @@protoc_insertion_point(field_get:ActionNtyItem.Z)
  return z_;
}
inline void ActionNtyItem::set_z(float value) {
  
  z_ = value;
  // @@protoc_insertion_point(field_set:ActionNtyItem.Z)
}

// float Ft = 11;
inline void ActionNtyItem::clear_ft() {
  ft_ = 0;
}
inline float ActionNtyItem::ft() const {
  // @@protoc_insertion_point(field_get:ActionNtyItem.Ft)
  return ft_;
}
inline void ActionNtyItem::set_ft(float value) {
  
  ft_ = value;
  // @@protoc_insertion_point(field_set:ActionNtyItem.Ft)
}

// int32 Hp = 12;
inline void ActionNtyItem::clear_hp() {
  hp_ = 0;
}
inline ::google::protobuf::int32 ActionNtyItem::hp() const {
  // @@protoc_insertion_point(field_get:ActionNtyItem.Hp)
  return hp_;
}
inline void ActionNtyItem::set_hp(::google::protobuf::int32 value) {
  
  hp_ = value;
  // @@protoc_insertion_point(field_set:ActionNtyItem.Hp)
}

// int32 Mp = 13;
inline void ActionNtyItem::clear_mp() {
  mp_ = 0;
}
inline ::google::protobuf::int32 ActionNtyItem::mp() const {
  // @@protoc_insertion_point(field_get:ActionNtyItem.Mp)
  return mp_;
}
inline void ActionNtyItem::set_mp(::google::protobuf::int32 value) {
  
  mp_ = value;
  // @@protoc_insertion_point(field_set:ActionNtyItem.Mp)
}

// int32 HpMax = 14;
inline void ActionNtyItem::clear_hpmax() {
  hpmax_ = 0;
}
inline ::google::protobuf::int32 ActionNtyItem::hpmax() const {
  // @@protoc_insertion_point(field_get:ActionNtyItem.HpMax)
  return hpmax_;
}
inline void ActionNtyItem::set_hpmax(::google::protobuf::int32 value) {
  
  hpmax_ = value;
  // @@protoc_insertion_point(field_set:ActionNtyItem.HpMax)
}

// int32 MpMax = 15;
inline void ActionNtyItem::clear_mpmax() {
  mpmax_ = 0;
}
inline ::google::protobuf::int32 ActionNtyItem::mpmax() const {
  // @@protoc_insertion_point(field_get:ActionNtyItem.MpMax)
  return mpmax_;
}
inline void ActionNtyItem::set_mpmax(::google::protobuf::int32 value) {
  
  mpmax_ = value;
  // @@protoc_insertion_point(field_set:ActionNtyItem.MpMax)
}

// -------------------------------------------------------------------

// ActionReqItem

// uint64 ObjectGuid = 1;
inline void ActionReqItem::clear_objectguid() {
  objectguid_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 ActionReqItem::objectguid() const {
  // @@protoc_insertion_point(field_get:ActionReqItem.ObjectGuid)
  return objectguid_;
}
inline void ActionReqItem::set_objectguid(::google::protobuf::uint64 value) {
  
  objectguid_ = value;
  // @@protoc_insertion_point(field_set:ActionReqItem.ObjectGuid)
}

// int32 ActionID = 2;
inline void ActionReqItem::clear_actionid() {
  actionid_ = 0;
}
inline ::google::protobuf::int32 ActionReqItem::actionid() const {
  // @@protoc_insertion_point(field_get:ActionReqItem.ActionID)
  return actionid_;
}
inline void ActionReqItem::set_actionid(::google::protobuf::int32 value) {
  
  actionid_ = value;
  // @@protoc_insertion_point(field_set:ActionReqItem.ActionID)
}

// int32 IsSkill = 3;
inline void ActionReqItem::clear_isskill() {
  isskill_ = 0;
}
inline ::google::protobuf::int32 ActionReqItem::isskill() const {
  // @@protoc_insertion_point(field_get:ActionReqItem.IsSkill)
  return isskill_;
}
inline void ActionReqItem::set_isskill(::google::protobuf::int32 value) {
  
  isskill_ = value;
  // @@protoc_insertion_point(field_set:ActionReqItem.IsSkill)
}

// float HostX = 4;
inline void ActionReqItem::clear_hostx() {
  hostx_ = 0;
}
inline float ActionReqItem::hostx() const {
  // @@protoc_insertion_point(field_get:ActionReqItem.HostX)
  return hostx_;
}
inline void ActionReqItem::set_hostx(float value) {
  
  hostx_ = value;
  // @@protoc_insertion_point(field_set:ActionReqItem.HostX)
}

// float HostY = 5;
inline void ActionReqItem::clear_hosty() {
  hosty_ = 0;
}
inline float ActionReqItem::hosty() const {
  // @@protoc_insertion_point(field_get:ActionReqItem.HostY)
  return hosty_;
}
inline void ActionReqItem::set_hosty(float value) {
  
  hosty_ = value;
  // @@protoc_insertion_point(field_set:ActionReqItem.HostY)
}

// float HostZ = 6;
inline void ActionReqItem::clear_hostz() {
  hostz_ = 0;
}
inline float ActionReqItem::hostz() const {
  // @@protoc_insertion_point(field_get:ActionReqItem.HostZ)
  return hostz_;
}
inline void ActionReqItem::set_hostz(float value) {
  
  hostz_ = value;
  // @@protoc_insertion_point(field_set:ActionReqItem.HostZ)
}

// float HostFt = 7;
inline void ActionReqItem::clear_hostft() {
  hostft_ = 0;
}
inline float ActionReqItem::hostft() const {
  // @@protoc_insertion_point(field_get:ActionReqItem.HostFt)
  return hostft_;
}
inline void ActionReqItem::set_hostft(float value) {
  
  hostft_ = value;
  // @@protoc_insertion_point(field_set:ActionReqItem.HostFt)
}

// float TargetX = 8;
inline void ActionReqItem::clear_targetx() {
  targetx_ = 0;
}
inline float ActionReqItem::targetx() const {
  // @@protoc_insertion_point(field_get:ActionReqItem.TargetX)
  return targetx_;
}
inline void ActionReqItem::set_targetx(float value) {
  
  targetx_ = value;
  // @@protoc_insertion_point(field_set:ActionReqItem.TargetX)
}

// float TargetY = 9;
inline void ActionReqItem::clear_targety() {
  targety_ = 0;
}
inline float ActionReqItem::targety() const {
  // @@protoc_insertion_point(field_get:ActionReqItem.TargetY)
  return targety_;
}
inline void ActionReqItem::set_targety(float value) {
  
  targety_ = value;
  // @@protoc_insertion_point(field_set:ActionReqItem.TargetY)
}

// float TargetZ = 10;
inline void ActionReqItem::clear_targetz() {
  targetz_ = 0;
}
inline float ActionReqItem::targetz() const {
  // @@protoc_insertion_point(field_get:ActionReqItem.TargetZ)
  return targetz_;
}
inline void ActionReqItem::set_targetz(float value) {
  
  targetz_ = value;
  // @@protoc_insertion_point(field_set:ActionReqItem.TargetZ)
}

// float TargetFt = 11;
inline void ActionReqItem::clear_targetft() {
  targetft_ = 0;
}
inline float ActionReqItem::targetft() const {
  // @@protoc_insertion_point(field_get:ActionReqItem.TargetFt)
  return targetft_;
}
inline void ActionReqItem::set_targetft(float value) {
  
  targetft_ = value;
  // @@protoc_insertion_point(field_set:ActionReqItem.TargetFt)
}

// repeated uint64 TargetObjects = 12;
inline int ActionReqItem::targetobjects_size() const {
  return targetobjects_.size();
}
inline void ActionReqItem::clear_targetobjects() {
  targetobjects_.Clear();
}
inline ::google::protobuf::uint64 ActionReqItem::targetobjects(int index) const {
  // @@protoc_insertion_point(field_get:ActionReqItem.TargetObjects)
  return targetobjects_.Get(index);
}
inline void ActionReqItem::set_targetobjects(int index, ::google::protobuf::uint64 value) {
  targetobjects_.Set(index, value);
  // @@protoc_insertion_point(field_set:ActionReqItem.TargetObjects)
}
inline void ActionReqItem::add_targetobjects(::google::protobuf::uint64 value) {
  targetobjects_.Add(value);
  // @@protoc_insertion_point(field_add:ActionReqItem.TargetObjects)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
ActionReqItem::targetobjects() const {
  // @@protoc_insertion_point(field_list:ActionReqItem.TargetObjects)
  return targetobjects_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
ActionReqItem::mutable_targetobjects() {
  // @@protoc_insertion_point(field_mutable_list:ActionReqItem.TargetObjects)
  return &targetobjects_;
}

// -------------------------------------------------------------------

// ObjectActionReq

// repeated .ActionReqItem ActionList = 1;
inline int ObjectActionReq::actionlist_size() const {
  return actionlist_.size();
}
inline void ObjectActionReq::clear_actionlist() {
  actionlist_.Clear();
}
inline const ::ActionReqItem& ObjectActionReq::actionlist(int index) const {
  // @@protoc_insertion_point(field_get:ObjectActionReq.ActionList)
  return actionlist_.Get(index);
}
inline ::ActionReqItem* ObjectActionReq::mutable_actionlist(int index) {
  // @@protoc_insertion_point(field_mutable:ObjectActionReq.ActionList)
  return actionlist_.Mutable(index);
}
inline ::ActionReqItem* ObjectActionReq::add_actionlist() {
  // @@protoc_insertion_point(field_add:ObjectActionReq.ActionList)
  return actionlist_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::ActionReqItem >*
ObjectActionReq::mutable_actionlist() {
  // @@protoc_insertion_point(field_mutable_list:ObjectActionReq.ActionList)
  return &actionlist_;
}
inline const ::google::protobuf::RepeatedPtrField< ::ActionReqItem >&
ObjectActionReq::actionlist() const {
  // @@protoc_insertion_point(field_list:ObjectActionReq.ActionList)
  return actionlist_;
}

// -------------------------------------------------------------------

// ObjectActionNty

// repeated .ActionNtyItem ActionList = 1;
inline int ObjectActionNty::actionlist_size() const {
  return actionlist_.size();
}
inline void ObjectActionNty::clear_actionlist() {
  actionlist_.Clear();
}
inline const ::ActionNtyItem& ObjectActionNty::actionlist(int index) const {
  // @@protoc_insertion_point(field_get:ObjectActionNty.ActionList)
  return actionlist_.Get(index);
}
inline ::ActionNtyItem* ObjectActionNty::mutable_actionlist(int index) {
  // @@protoc_insertion_point(field_mutable:ObjectActionNty.ActionList)
  return actionlist_.Mutable(index);
}
inline ::ActionNtyItem* ObjectActionNty::add_actionlist() {
  // @@protoc_insertion_point(field_add:ObjectActionNty.ActionList)
  return actionlist_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::ActionNtyItem >*
ObjectActionNty::mutable_actionlist() {
  // @@protoc_insertion_point(field_mutable_list:ObjectActionNty.ActionList)
  return &actionlist_;
}
inline const ::google::protobuf::RepeatedPtrField< ::ActionNtyItem >&
ObjectActionNty::actionlist() const {
  // @@protoc_insertion_point(field_list:ObjectActionNty.ActionList)
  return actionlist_;
}

// -------------------------------------------------------------------

// NewItem

// uint64 ObjectGuid = 1;
inline void NewItem::clear_objectguid() {
  objectguid_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 NewItem::objectguid() const {
  // @@protoc_insertion_point(field_get:NewItem.ObjectGuid)
  return objectguid_;
}
inline void NewItem::set_objectguid(::google::protobuf::uint64 value) {
  
  objectguid_ = value;
  // @@protoc_insertion_point(field_set:NewItem.ObjectGuid)
}

// int32 ObjType = 2;
inline void NewItem::clear_objtype() {
  objtype_ = 0;
}
inline ::google::protobuf::int32 NewItem::objtype() const {
  // @@protoc_insertion_point(field_get:NewItem.ObjType)
  return objtype_;
}
inline void NewItem::set_objtype(::google::protobuf::int32 value) {
  
  objtype_ = value;
  // @@protoc_insertion_point(field_set:NewItem.ObjType)
}

// int32 ObjStatue = 3;
inline void NewItem::clear_objstatue() {
  objstatue_ = 0;
}
inline ::google::protobuf::int32 NewItem::objstatue() const {
  // @@protoc_insertion_point(field_get:NewItem.ObjStatue)
  return objstatue_;
}
inline void NewItem::set_objstatue(::google::protobuf::int32 value) {
  
  objstatue_ = value;
  // @@protoc_insertion_point(field_set:NewItem.ObjStatue)
}

// int32 ActorID = 4;
inline void NewItem::clear_actorid() {
  actorid_ = 0;
}
inline ::google::protobuf::int32 NewItem::actorid() const {
  // @@protoc_insertion_point(field_get:NewItem.ActorID)
  return actorid_;
}
inline void NewItem::set_actorid(::google::protobuf::int32 value) {
  
  actorid_ = value;
  // @@protoc_insertion_point(field_set:NewItem.ActorID)
}

// string Name = 5;
inline void NewItem::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& NewItem::name() const {
  // @@protoc_insertion_point(field_get:NewItem.Name)
  return name_.GetNoArena();
}
inline void NewItem::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:NewItem.Name)
}
#if LANG_CXX11
inline void NewItem::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:NewItem.Name)
}
#endif
inline void NewItem::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:NewItem.Name)
}
inline void NewItem::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:NewItem.Name)
}
inline ::std::string* NewItem::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:NewItem.Name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* NewItem::release_name() {
  // @@protoc_insertion_point(field_release:NewItem.Name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void NewItem::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:NewItem.Name)
}

// int32 Level = 6;
inline void NewItem::clear_level() {
  level_ = 0;
}
inline ::google::protobuf::int32 NewItem::level() const {
  // @@protoc_insertion_point(field_get:NewItem.Level)
  return level_;
}
inline void NewItem::set_level(::google::protobuf::int32 value) {
  
  level_ = value;
  // @@protoc_insertion_point(field_set:NewItem.Level)
}

// uint64 HostGuid = 7;
inline void NewItem::clear_hostguid() {
  hostguid_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 NewItem::hostguid() const {
  // @@protoc_insertion_point(field_get:NewItem.HostGuid)
  return hostguid_;
}
inline void NewItem::set_hostguid(::google::protobuf::uint64 value) {
  
  hostguid_ = value;
  // @@protoc_insertion_point(field_set:NewItem.HostGuid)
}

// uint64 ControlerID = 8;
inline void NewItem::clear_controlerid() {
  controlerid_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 NewItem::controlerid() const {
  // @@protoc_insertion_point(field_get:NewItem.ControlerID)
  return controlerid_;
}
inline void NewItem::set_controlerid(::google::protobuf::uint64 value) {
  
  controlerid_ = value;
  // @@protoc_insertion_point(field_set:NewItem.ControlerID)
}

// uint64 SummonID = 9;
inline void NewItem::clear_summonid() {
  summonid_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 NewItem::summonid() const {
  // @@protoc_insertion_point(field_get:NewItem.SummonID)
  return summonid_;
}
inline void NewItem::set_summonid(::google::protobuf::uint64 value) {
  
  summonid_ = value;
  // @@protoc_insertion_point(field_set:NewItem.SummonID)
}

// float X = 10;
inline void NewItem::clear_x() {
  x_ = 0;
}
inline float NewItem::x() const {
  // @@protoc_insertion_point(field_get:NewItem.X)
  return x_;
}
inline void NewItem::set_x(float value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:NewItem.X)
}

// float Y = 11;
inline void NewItem::clear_y() {
  y_ = 0;
}
inline float NewItem::y() const {
  // @@protoc_insertion_point(field_get:NewItem.Y)
  return y_;
}
inline void NewItem::set_y(float value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:NewItem.Y)
}

// float Z = 12;
inline void NewItem::clear_z() {
  z_ = 0;
}
inline float NewItem::z() const {
  // @@protoc_insertion_point(field_get:NewItem.Z)
  return z_;
}
inline void NewItem::set_z(float value) {
  
  z_ = value;
  // @@protoc_insertion_point(field_set:NewItem.Z)
}

// float Ft = 13;
inline void NewItem::clear_ft() {
  ft_ = 0;
}
inline float NewItem::ft() const {
  // @@protoc_insertion_point(field_get:NewItem.Ft)
  return ft_;
}
inline void NewItem::set_ft(float value) {
  
  ft_ = value;
  // @@protoc_insertion_point(field_set:NewItem.Ft)
}

// int32 Hp = 14;
inline void NewItem::clear_hp() {
  hp_ = 0;
}
inline ::google::protobuf::int32 NewItem::hp() const {
  // @@protoc_insertion_point(field_get:NewItem.Hp)
  return hp_;
}
inline void NewItem::set_hp(::google::protobuf::int32 value) {
  
  hp_ = value;
  // @@protoc_insertion_point(field_set:NewItem.Hp)
}

// int32 Mp = 15;
inline void NewItem::clear_mp() {
  mp_ = 0;
}
inline ::google::protobuf::int32 NewItem::mp() const {
  // @@protoc_insertion_point(field_get:NewItem.Mp)
  return mp_;
}
inline void NewItem::set_mp(::google::protobuf::int32 value) {
  
  mp_ = value;
  // @@protoc_insertion_point(field_set:NewItem.Mp)
}

// int32 HpMax = 16;
inline void NewItem::clear_hpmax() {
  hpmax_ = 0;
}
inline ::google::protobuf::int32 NewItem::hpmax() const {
  // @@protoc_insertion_point(field_get:NewItem.HpMax)
  return hpmax_;
}
inline void NewItem::set_hpmax(::google::protobuf::int32 value) {
  
  hpmax_ = value;
  // @@protoc_insertion_point(field_set:NewItem.HpMax)
}

// int32 MpMax = 17;
inline void NewItem::clear_mpmax() {
  mpmax_ = 0;
}
inline ::google::protobuf::int32 NewItem::mpmax() const {
  // @@protoc_insertion_point(field_get:NewItem.MpMax)
  return mpmax_;
}
inline void NewItem::set_mpmax(::google::protobuf::int32 value) {
  
  mpmax_ = value;
  // @@protoc_insertion_point(field_set:NewItem.MpMax)
}

// int32 Weapon = 18;
inline void NewItem::clear_weapon() {
  weapon_ = 0;
}
inline ::google::protobuf::int32 NewItem::weapon() const {
  // @@protoc_insertion_point(field_get:NewItem.Weapon)
  return weapon_;
}
inline void NewItem::set_weapon(::google::protobuf::int32 value) {
  
  weapon_ = value;
  // @@protoc_insertion_point(field_set:NewItem.Weapon)
}

// -------------------------------------------------------------------

// ObjectNewNty

// repeated .NewItem NewList = 1;
inline int ObjectNewNty::newlist_size() const {
  return newlist_.size();
}
inline void ObjectNewNty::clear_newlist() {
  newlist_.Clear();
}
inline const ::NewItem& ObjectNewNty::newlist(int index) const {
  // @@protoc_insertion_point(field_get:ObjectNewNty.NewList)
  return newlist_.Get(index);
}
inline ::NewItem* ObjectNewNty::mutable_newlist(int index) {
  // @@protoc_insertion_point(field_mutable:ObjectNewNty.NewList)
  return newlist_.Mutable(index);
}
inline ::NewItem* ObjectNewNty::add_newlist() {
  // @@protoc_insertion_point(field_add:ObjectNewNty.NewList)
  return newlist_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::NewItem >*
ObjectNewNty::mutable_newlist() {
  // @@protoc_insertion_point(field_mutable_list:ObjectNewNty.NewList)
  return &newlist_;
}
inline const ::google::protobuf::RepeatedPtrField< ::NewItem >&
ObjectNewNty::newlist() const {
  // @@protoc_insertion_point(field_list:ObjectNewNty.NewList)
  return newlist_;
}

// -------------------------------------------------------------------

// ObjectRemoveNty

// repeated uint64 RemoveList = 1;
inline int ObjectRemoveNty::removelist_size() const {
  return removelist_.size();
}
inline void ObjectRemoveNty::clear_removelist() {
  removelist_.Clear();
}
inline ::google::protobuf::uint64 ObjectRemoveNty::removelist(int index) const {
  // @@protoc_insertion_point(field_get:ObjectRemoveNty.RemoveList)
  return removelist_.Get(index);
}
inline void ObjectRemoveNty::set_removelist(int index, ::google::protobuf::uint64 value) {
  removelist_.Set(index, value);
  // @@protoc_insertion_point(field_set:ObjectRemoveNty.RemoveList)
}
inline void ObjectRemoveNty::add_removelist(::google::protobuf::uint64 value) {
  removelist_.Add(value);
  // @@protoc_insertion_point(field_add:ObjectRemoveNty.RemoveList)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
ObjectRemoveNty::removelist() const {
  // @@protoc_insertion_point(field_list:ObjectRemoveNty.RemoveList)
  return removelist_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
ObjectRemoveNty::mutable_removelist() {
  // @@protoc_insertion_point(field_mutable_list:ObjectRemoveNty.RemoveList)
  return &removelist_;
}

// -------------------------------------------------------------------

// HeartBeatReq

// uint32 TimeStamp = 1;
inline void HeartBeatReq::clear_timestamp() {
  timestamp_ = 0u;
}
inline ::google::protobuf::uint32 HeartBeatReq::timestamp() const {
  // @@protoc_insertion_point(field_get:HeartBeatReq.TimeStamp)
  return timestamp_;
}
inline void HeartBeatReq::set_timestamp(::google::protobuf::uint32 value) {
  
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:HeartBeatReq.TimeStamp)
}

// -------------------------------------------------------------------

// HeartBeatAck

// uint32 TimeStamp = 1;
inline void HeartBeatAck::clear_timestamp() {
  timestamp_ = 0u;
}
inline ::google::protobuf::uint32 HeartBeatAck::timestamp() const {
  // @@protoc_insertion_point(field_get:HeartBeatAck.TimeStamp)
  return timestamp_;
}
inline void HeartBeatAck::set_timestamp(::google::protobuf::uint32 value) {
  
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:HeartBeatAck.TimeStamp)
}

// uint32 ServerTime = 2;
inline void HeartBeatAck::clear_servertime() {
  servertime_ = 0u;
}
inline ::google::protobuf::uint32 HeartBeatAck::servertime() const {
  // @@protoc_insertion_point(field_get:HeartBeatAck.ServerTime)
  return servertime_;
}
inline void HeartBeatAck::set_servertime(::google::protobuf::uint32 value) {
  
  servertime_ = value;
  // @@protoc_insertion_point(field_set:HeartBeatAck.ServerTime)
}

// -------------------------------------------------------------------

// ObjectDieNotify

// uint64 ObjectGuid = 1;
inline void ObjectDieNotify::clear_objectguid() {
  objectguid_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 ObjectDieNotify::objectguid() const {
  // @@protoc_insertion_point(field_get:ObjectDieNotify.ObjectGuid)
  return objectguid_;
}
inline void ObjectDieNotify::set_objectguid(::google::protobuf::uint64 value) {
  
  objectguid_ = value;
  // @@protoc_insertion_point(field_set:ObjectDieNotify.ObjectGuid)
}

// -------------------------------------------------------------------

// ObjectValueChange

// uint64 TargetGUID = 1;
inline void ObjectValueChange::clear_targetguid() {
  targetguid_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 ObjectValueChange::targetguid() const {
  // @@protoc_insertion_point(field_get:ObjectValueChange.TargetGUID)
  return targetguid_;
}
inline void ObjectValueChange::set_targetguid(::google::protobuf::uint64 value) {
  
  targetguid_ = value;
  // @@protoc_insertion_point(field_set:ObjectValueChange.TargetGUID)
}

// int32 ValueID = 2;
inline void ObjectValueChange::clear_valueid() {
  valueid_ = 0;
}
inline ::google::protobuf::int32 ObjectValueChange::valueid() const {
  // @@protoc_insertion_point(field_get:ObjectValueChange.ValueID)
  return valueid_;
}
inline void ObjectValueChange::set_valueid(::google::protobuf::int32 value) {
  
  valueid_ = value;
  // @@protoc_insertion_point(field_set:ObjectValueChange.ValueID)
}

// int32 Value = 3;
inline void ObjectValueChange::clear_value() {
  value_ = 0;
}
inline ::google::protobuf::int32 ObjectValueChange::value() const {
  // @@protoc_insertion_point(field_get:ObjectValueChange.Value)
  return value_;
}
inline void ObjectValueChange::set_value(::google::protobuf::int32 value) {
  
  value_ = value;
  // @@protoc_insertion_point(field_set:ObjectValueChange.Value)
}

// bool Crit = 4;
inline void ObjectValueChange::clear_crit() {
  crit_ = false;
}
inline bool ObjectValueChange::crit() const {
  // @@protoc_insertion_point(field_get:ObjectValueChange.Crit)
  return crit_;
}
inline void ObjectValueChange::set_crit(bool value) {
  
  crit_ = value;
  // @@protoc_insertion_point(field_set:ObjectValueChange.Crit)
}

// -------------------------------------------------------------------

// ObjectValueChangeNtf

// repeated .ObjectValueChange ChangeList = 1;
inline int ObjectValueChangeNtf::changelist_size() const {
  return changelist_.size();
}
inline void ObjectValueChangeNtf::clear_changelist() {
  changelist_.Clear();
}
inline const ::ObjectValueChange& ObjectValueChangeNtf::changelist(int index) const {
  // @@protoc_insertion_point(field_get:ObjectValueChangeNtf.ChangeList)
  return changelist_.Get(index);
}
inline ::ObjectValueChange* ObjectValueChangeNtf::mutable_changelist(int index) {
  // @@protoc_insertion_point(field_mutable:ObjectValueChangeNtf.ChangeList)
  return changelist_.Mutable(index);
}
inline ::ObjectValueChange* ObjectValueChangeNtf::add_changelist() {
  // @@protoc_insertion_point(field_add:ObjectValueChangeNtf.ChangeList)
  return changelist_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::ObjectValueChange >*
ObjectValueChangeNtf::mutable_changelist() {
  // @@protoc_insertion_point(field_mutable_list:ObjectValueChangeNtf.ChangeList)
  return &changelist_;
}
inline const ::google::protobuf::RepeatedPtrField< ::ObjectValueChange >&
ObjectValueChangeNtf::changelist() const {
  // @@protoc_insertion_point(field_list:ObjectValueChangeNtf.ChangeList)
  return changelist_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Msg_5fMove_2eproto__INCLUDED
