// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Msg_Bag.proto

#ifndef PROTOBUF_Msg_5fBag_2eproto__INCLUDED
#define PROTOBUF_Msg_5fBag_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
class BagDataNty;
class BagDataNtyDefaultTypeInternal;
extern BagDataNtyDefaultTypeInternal _BagDataNty_default_instance_;
class BagItem;
class BagItemDefaultTypeInternal;
extern BagItemDefaultTypeInternal _BagItem_default_instance_;

namespace protobuf_Msg_5fBag_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_Msg_5fBag_2eproto

// ===================================================================

class BagItem : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:BagItem) */ {
 public:
  BagItem();
  virtual ~BagItem();

  BagItem(const BagItem& from);

  inline BagItem& operator=(const BagItem& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const BagItem& default_instance();

  static inline const BagItem* internal_default_instance() {
    return reinterpret_cast<const BagItem*>(
               &_BagItem_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(BagItem* other);

  // implements Message ----------------------------------------------

  inline BagItem* New() const PROTOBUF_FINAL { return New(NULL); }

  BagItem* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const BagItem& from);
  void MergeFrom(const BagItem& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(BagItem* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 Guid = 1;
  void clear_guid();
  static const int kGuidFieldNumber = 1;
  ::google::protobuf::uint64 guid() const;
  void set_guid(::google::protobuf::uint64 value);

  // int32 ItemID = 2;
  void clear_itemid();
  static const int kItemIDFieldNumber = 2;
  ::google::protobuf::int32 itemid() const;
  void set_itemid(::google::protobuf::int32 value);

  // int32 ItemNum = 3;
  void clear_itemnum();
  static const int kItemNumFieldNumber = 3;
  ::google::protobuf::int32 itemnum() const;
  void set_itemnum(::google::protobuf::int32 value);

  // int32 ItemGuid = 4;
  void clear_itemguid();
  static const int kItemGuidFieldNumber = 4;
  ::google::protobuf::int32 itemguid() const;
  void set_itemguid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:BagItem)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint64 guid_;
  ::google::protobuf::int32 itemid_;
  ::google::protobuf::int32 itemnum_;
  ::google::protobuf::int32 itemguid_;
  mutable int _cached_size_;
  friend struct protobuf_Msg_5fBag_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class BagDataNty : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:BagDataNty) */ {
 public:
  BagDataNty();
  virtual ~BagDataNty();

  BagDataNty(const BagDataNty& from);

  inline BagDataNty& operator=(const BagDataNty& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const BagDataNty& default_instance();

  static inline const BagDataNty* internal_default_instance() {
    return reinterpret_cast<const BagDataNty*>(
               &_BagDataNty_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(BagDataNty* other);

  // implements Message ----------------------------------------------

  inline BagDataNty* New() const PROTOBUF_FINAL { return New(NULL); }

  BagDataNty* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const BagDataNty& from);
  void MergeFrom(const BagDataNty& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(BagDataNty* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .BagItem ChangeList = 1;
  int changelist_size() const;
  void clear_changelist();
  static const int kChangeListFieldNumber = 1;
  const ::BagItem& changelist(int index) const;
  ::BagItem* mutable_changelist(int index);
  ::BagItem* add_changelist();
  ::google::protobuf::RepeatedPtrField< ::BagItem >*
      mutable_changelist();
  const ::google::protobuf::RepeatedPtrField< ::BagItem >&
      changelist() const;

  // repeated uint64 RemoveList = 2;
  int removelist_size() const;
  void clear_removelist();
  static const int kRemoveListFieldNumber = 2;
  ::google::protobuf::uint64 removelist(int index) const;
  void set_removelist(int index, ::google::protobuf::uint64 value);
  void add_removelist(::google::protobuf::uint64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
      removelist() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
      mutable_removelist();

  // @@protoc_insertion_point(class_scope:BagDataNty)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::BagItem > changelist_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 > removelist_;
  mutable int _removelist_cached_byte_size_;
  mutable int _cached_size_;
  friend struct protobuf_Msg_5fBag_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// BagItem

// uint64 Guid = 1;
inline void BagItem::clear_guid() {
  guid_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 BagItem::guid() const {
  // @@protoc_insertion_point(field_get:BagItem.Guid)
  return guid_;
}
inline void BagItem::set_guid(::google::protobuf::uint64 value) {
  
  guid_ = value;
  // @@protoc_insertion_point(field_set:BagItem.Guid)
}

// int32 ItemID = 2;
inline void BagItem::clear_itemid() {
  itemid_ = 0;
}
inline ::google::protobuf::int32 BagItem::itemid() const {
  // @@protoc_insertion_point(field_get:BagItem.ItemID)
  return itemid_;
}
inline void BagItem::set_itemid(::google::protobuf::int32 value) {
  
  itemid_ = value;
  // @@protoc_insertion_point(field_set:BagItem.ItemID)
}

// int32 ItemNum = 3;
inline void BagItem::clear_itemnum() {
  itemnum_ = 0;
}
inline ::google::protobuf::int32 BagItem::itemnum() const {
  // @@protoc_insertion_point(field_get:BagItem.ItemNum)
  return itemnum_;
}
inline void BagItem::set_itemnum(::google::protobuf::int32 value) {
  
  itemnum_ = value;
  // @@protoc_insertion_point(field_set:BagItem.ItemNum)
}

// int32 ItemGuid = 4;
inline void BagItem::clear_itemguid() {
  itemguid_ = 0;
}
inline ::google::protobuf::int32 BagItem::itemguid() const {
  // @@protoc_insertion_point(field_get:BagItem.ItemGuid)
  return itemguid_;
}
inline void BagItem::set_itemguid(::google::protobuf::int32 value) {
  
  itemguid_ = value;
  // @@protoc_insertion_point(field_set:BagItem.ItemGuid)
}

// -------------------------------------------------------------------

// BagDataNty

// repeated .BagItem ChangeList = 1;
inline int BagDataNty::changelist_size() const {
  return changelist_.size();
}
inline void BagDataNty::clear_changelist() {
  changelist_.Clear();
}
inline const ::BagItem& BagDataNty::changelist(int index) const {
  // @@protoc_insertion_point(field_get:BagDataNty.ChangeList)
  return changelist_.Get(index);
}
inline ::BagItem* BagDataNty::mutable_changelist(int index) {
  // @@protoc_insertion_point(field_mutable:BagDataNty.ChangeList)
  return changelist_.Mutable(index);
}
inline ::BagItem* BagDataNty::add_changelist() {
  // @@protoc_insertion_point(field_add:BagDataNty.ChangeList)
  return changelist_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::BagItem >*
BagDataNty::mutable_changelist() {
  // @@protoc_insertion_point(field_mutable_list:BagDataNty.ChangeList)
  return &changelist_;
}
inline const ::google::protobuf::RepeatedPtrField< ::BagItem >&
BagDataNty::changelist() const {
  // @@protoc_insertion_point(field_list:BagDataNty.ChangeList)
  return changelist_;
}

// repeated uint64 RemoveList = 2;
inline int BagDataNty::removelist_size() const {
  return removelist_.size();
}
inline void BagDataNty::clear_removelist() {
  removelist_.Clear();
}
inline ::google::protobuf::uint64 BagDataNty::removelist(int index) const {
  // @@protoc_insertion_point(field_get:BagDataNty.RemoveList)
  return removelist_.Get(index);
}
inline void BagDataNty::set_removelist(int index, ::google::protobuf::uint64 value) {
  removelist_.Set(index, value);
  // @@protoc_insertion_point(field_set:BagDataNty.RemoveList)
}
inline void BagDataNty::add_removelist(::google::protobuf::uint64 value) {
  removelist_.Add(value);
  // @@protoc_insertion_point(field_add:BagDataNty.RemoveList)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
BagDataNty::removelist() const {
  // @@protoc_insertion_point(field_list:BagDataNty.RemoveList)
  return removelist_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
BagDataNty::mutable_removelist() {
  // @@protoc_insertion_point(field_mutable_list:BagDataNty.RemoveList)
  return &removelist_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Msg_5fBag_2eproto__INCLUDED
