//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: MessageEquip.proto
// Note: requires additional types generated from: MessageID.proto
// Note: requires additional types generated from: MessageRetCode.proto
// Note: requires additional types generated from: MessageCommon.proto
namespace Protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqUpStarEquip")]
  public partial class ReqUpStarEquip : global::ProtoBuf.IExtensible
  {
    public ReqUpStarEquip() {}
    
    private Protocol.XEquip _TarEquip;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"TarEquip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Protocol.XEquip TarEquip
    {
      get { return _TarEquip; }
      set { _TarEquip = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AckUpStarEquip")]
  public partial class AckUpStarEquip : global::ProtoBuf.IExtensible
  {
    public AckUpStarEquip() {}
    
    private Protocol.XEquip _TarEquip;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"TarEquip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Protocol.XEquip TarEquip
    {
      get { return _TarEquip; }
      set { _TarEquip = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqStrengthEquip")]
  public partial class ReqStrengthEquip : global::ProtoBuf.IExtensible
  {
    public ReqStrengthEquip() {}
    
    private Protocol.XEquip _TarEquip;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"TarEquip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Protocol.XEquip TarEquip
    {
      get { return _TarEquip; }
      set { _TarEquip = value; }
    }
    private readonly global::System.Collections.Generic.List<Protocol.XItem> _UseItems = new global::System.Collections.Generic.List<Protocol.XItem>();
    [global::ProtoBuf.ProtoMember(2, Name=@"UseItems", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Protocol.XItem> UseItems
    {
      get { return _UseItems; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AckStrengthEquip")]
  public partial class AckStrengthEquip : global::ProtoBuf.IExtensible
  {
    public AckStrengthEquip() {}
    
    private Protocol.XEquip _TarEquip;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"TarEquip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Protocol.XEquip TarEquip
    {
      get { return _TarEquip; }
      set { _TarEquip = value; }
    }
    private readonly global::System.Collections.Generic.List<Protocol.XItem> _UseItems = new global::System.Collections.Generic.List<Protocol.XItem>();
    [global::ProtoBuf.ProtoMember(2, Name=@"UseItems", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Protocol.XItem> UseItems
    {
      get { return _UseItems; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqAdvanceEquip")]
  public partial class ReqAdvanceEquip : global::ProtoBuf.IExtensible
  {
    public ReqAdvanceEquip() {}
    
    private Protocol.XEquip _TarEquip;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"TarEquip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Protocol.XEquip TarEquip
    {
      get { return _TarEquip; }
      set { _TarEquip = value; }
    }
    private readonly global::System.Collections.Generic.List<Protocol.XItem> _UseItems = new global::System.Collections.Generic.List<Protocol.XItem>();
    [global::ProtoBuf.ProtoMember(2, Name=@"UseItems", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Protocol.XItem> UseItems
    {
      get { return _UseItems; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AckAdvanceEquip")]
  public partial class AckAdvanceEquip : global::ProtoBuf.IExtensible
  {
    public AckAdvanceEquip() {}
    
    private Protocol.XEquip _TarEquip;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"TarEquip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Protocol.XEquip TarEquip
    {
      get { return _TarEquip; }
      set { _TarEquip = value; }
    }
    private readonly global::System.Collections.Generic.List<Protocol.XItem> _UseItems = new global::System.Collections.Generic.List<Protocol.XItem>();
    [global::ProtoBuf.ProtoMember(2, Name=@"UseItems", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Protocol.XItem> UseItems
    {
      get { return _UseItems; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}