//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: MessageCommon.proto
namespace Protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"XItem")]
  public partial class XItem : global::ProtoBuf.IExtensible
  {
    public XItem() {}
    
    private int _Pos;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Pos
    {
      get { return _Pos; }
      set { _Pos = value; }
    }
    private int _Instance;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Instance", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Instance
    {
      get { return _Instance; }
      set { _Instance = value; }
    }
    private int _PosType;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"PosType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int PosType
    {
      get { return _PosType; }
      set { _PosType = value; }
    }
    private int _Id;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private int _Num;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"Num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Num
    {
      get { return _Num; }
      set { _Num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"XServer")]
  public partial class XServer : global::ProtoBuf.IExtensible
  {
    public XServer() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private string _Addr;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Addr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Addr
    {
      get { return _Addr; }
      set { _Addr = value; }
    }
    private string _Name;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private int _Area;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Area", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Area
    {
      get { return _Area; }
      set { _Area = value; }
    }
    private int _State;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"State", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int State
    {
      get { return _State; }
      set { _State = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"XAction")]
  public partial class XAction : global::ProtoBuf.IExtensible
  {
    public XAction() {}
    
    private int _Id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private int _Num;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Num
    {
      get { return _Num; }
      set { _Num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"XMoney")]
  public partial class XMoney : global::ProtoBuf.IExtensible
  {
    public XMoney() {}
    
    private int _Id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private int _Num;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Num
    {
      get { return _Num; }
      set { _Num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"XEquip")]
  public partial class XEquip : global::ProtoBuf.IExtensible
  {
    public XEquip() {}
    
    private int _Instance;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Instance", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Instance
    {
      get { return _Instance; }
      set { _Instance = value; }
    }
    private int _Id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private int _StrengthenLevel;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"StrengthenLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int StrengthenLevel
    {
      get { return _StrengthenLevel; }
      set { _StrengthenLevel = value; }
    }
    private int _StrengthenExp;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"StrengthenExp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int StrengthenExp
    {
      get { return _StrengthenExp; }
      set { _StrengthenExp = value; }
    }
    private int _StarLevel;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"StarLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int StarLevel
    {
      get { return _StarLevel; }
      set { _StarLevel = value; }
    }
    private int _AdvanceLevel;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"AdvanceLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int AdvanceLevel
    {
      get { return _AdvanceLevel; }
      set { _AdvanceLevel = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"XGem")]
  public partial class XGem : global::ProtoBuf.IExtensible
  {
    public XGem() {}
    
    private int _Instance;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Instance", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Instance
    {
      get { return _Instance; }
      set { _Instance = value; }
    }
    private int _Id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private int _StrengthenLevel;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"StrengthenLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int StrengthenLevel
    {
      get { return _StrengthenLevel; }
      set { _StrengthenLevel = value; }
    }
    private int _StrengthenExp;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"StrengthenExp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int StrengthenExp
    {
      get { return _StrengthenExp; }
      set { _StrengthenExp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"XVector3")]
  public partial class XVector3 : global::ProtoBuf.IExtensible
  {
    public XVector3() {}
    
    private float _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private float _z;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float z
    {
      get { return _z; }
      set { _z = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"XTransform")]
  public partial class XTransform : global::ProtoBuf.IExtensible
  {
    public XTransform() {}
    
    private Protocol.XVector3 _Pos;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Protocol.XVector3 Pos
    {
      get { return _Pos; }
      set { _Pos = value; }
    }
    private Protocol.XVector3 _Forward;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Forward", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Protocol.XVector3 Forward
    {
      get { return _Forward; }
      set { _Forward = value; }
    }
    private float _Speed;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Speed", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float Speed
    {
      get { return _Speed; }
      set { _Speed = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"XCopy")]
  public partial class XCopy : global::ProtoBuf.IExtensible
  {
    public XCopy() {}
    
    private int _Id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private int _StarNum;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"StarNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int StarNum
    {
      get { return _StarNum; }
      set { _StarNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"XDamage")]
  public partial class XDamage : global::ProtoBuf.IExtensible
  {
    public XDamage() {}
    
    private int _Value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Value
    {
      get { return _Value; }
      set { _Value = value; }
    }
    private int _Type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Type
    {
      get { return _Type; }
      set { _Type = value; }
    }
    private string _AttackerName;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"AttackerName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string AttackerName
    {
      get { return _AttackerName; }
      set { _AttackerName = value; }
    }
    private string _DefenderName;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"DefenderName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string DefenderName
    {
      get { return _DefenderName; }
      set { _DefenderName = value; }
    }
    private string _Skill;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"Skill", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Skill
    {
      get { return _Skill; }
      set { _Skill = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"XMainChapter")]
  public partial class XMainChapter : global::ProtoBuf.IExtensible
  {
    public XMainChapter() {}
    
    private int _Id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private int _Award1;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Award1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Award1
    {
      get { return _Award1; }
      set { _Award1 = value; }
    }
    private int _Award2;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Award2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Award2
    {
      get { return _Award2; }
      set { _Award2 = value; }
    }
    private int _Award3;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Award3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Award3
    {
      get { return _Award3; }
      set { _Award3 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"XMount")]
  public partial class XMount : global::ProtoBuf.IExtensible
  {
    public XMount() {}
    
    private int _Id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private int _Level;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Level
    {
      get { return _Level; }
      set { _Level = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"XPartner")]
  public partial class XPartner : global::ProtoBuf.IExtensible
  {
    public XPartner() {}
    
    private int _Id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private int _Level;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Level
    {
      get { return _Level; }
      set { _Level = value; }
    }
    private int _Advance;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Advance", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Advance
    {
      get { return _Advance; }
      set { _Advance = value; }
    }
    private int _Star;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Star", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Star
    {
      get { return _Star; }
      set { _Star = value; }
    }
    private int _Exp;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"Exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Exp
    {
      get { return _Exp; }
      set { _Exp = value; }
    }
    private int _Wake;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"Wake", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Wake
    {
      get { return _Wake; }
      set { _Wake = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"XPet")]
  public partial class XPet : global::ProtoBuf.IExtensible
  {
    public XPet() {}
    
    private int _Id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private int _Level;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Level
    {
      get { return _Level; }
      set { _Level = value; }
    }
    private int _CurExp;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"CurExp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int CurExp
    {
      get { return _CurExp; }
      set { _CurExp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"XRaid")]
  public partial class XRaid : global::ProtoBuf.IExtensible
  {
    public XRaid() {}
    
    private int _Id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private int _MaxChapter;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"MaxChapter", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int MaxChapter
    {
      get { return _MaxChapter; }
      set { _MaxChapter = value; }
    }
    private int _MaxCopyId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"MaxCopyId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int MaxCopyId
    {
      get { return _MaxCopyId; }
      set { _MaxCopyId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"XRelics")]
  public partial class XRelics : global::ProtoBuf.IExtensible
  {
    public XRelics() {}
    
    private int _Id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private int _Level;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Level
    {
      get { return _Level; }
      set { _Level = value; }
    }
    private int _CurExp1;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"CurExp1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int CurExp1
    {
      get { return _CurExp1; }
      set { _CurExp1 = value; }
    }
    private int _CurExp2;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"CurExp2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int CurExp2
    {
      get { return _CurExp2; }
      set { _CurExp2 = value; }
    }
    private int _CurExp3;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"CurExp3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int CurExp3
    {
      get { return _CurExp3; }
      set { _CurExp3 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"XRune")]
  public partial class XRune : global::ProtoBuf.IExtensible
  {
    public XRune() {}
    
    private int _Id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private int _Level;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Level
    {
      get { return _Level; }
      set { _Level = value; }
    }
    private int _Instance;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Instance", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Instance
    {
      get { return _Instance; }
      set { _Instance = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"XSkill")]
  public partial class XSkill : global::ProtoBuf.IExtensible
  {
    public XSkill() {}
    
    private int _Id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private int _Level;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Level
    {
      get { return _Level; }
      set { _Level = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"XSoul")]
  public partial class XSoul : global::ProtoBuf.IExtensible
  {
    public XSoul() {}
    
    private int _Id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private int _Num;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Num
    {
      get { return _Num; }
      set { _Num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"XTaskBranch")]
  public partial class XTaskBranch : global::ProtoBuf.IExtensible
  {
    public XTaskBranch() {}
    
    private int _Id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"XTaskDaily")]
  public partial class XTaskDaily : global::ProtoBuf.IExtensible
  {
    public XTaskDaily() {}
    
    private int _Id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private int _Count;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Count
    {
      get { return _Count; }
      set { _Count = value; }
    }
    private int _State;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"State", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int State
    {
      get { return _State; }
      set { _State = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"XTaskThread")]
  public partial class XTaskThread : global::ProtoBuf.IExtensible
  {
    public XTaskThread() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"XGuide")]
  public partial class XGuide : global::ProtoBuf.IExtensible
  {
    public XGuide() {}
    
    private int _Id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"XCharacter")]
  public partial class XCharacter : global::ProtoBuf.IExtensible
  {
    public XCharacter() {}
    
    private int _Id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private int _GUID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"GUID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int GUID
    {
      get { return _GUID; }
      set { _GUID = value; }
    }
    private string _Name;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private int _Sex;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Sex
    {
      get { return _Sex; }
      set { _Sex = value; }
    }
    private int _Level;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"Level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Level
    {
      get { return _Level; }
      set { _Level = value; }
    }
    private int _Title;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"Title", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Title
    {
      get { return _Title; }
      set { _Title = value; }
    }
    private int _Type;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Type
    {
      get { return _Type; }
      set { _Type = value; }
    }
    private int _Camp;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"Camp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Camp
    {
      get { return _Camp; }
      set { _Camp = value; }
    }
    private int _Sort;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"Sort", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Sort
    {
      get { return _Sort; }
      set { _Sort = value; }
    }
    private int _Race;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"Race", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Race
    {
      get { return _Race; }
      set { _Race = value; }
    }
    private int _Unit;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"Unit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Unit
    {
      get { return _Unit; }
      set { _Unit = value; }
    }
    private int _Group;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"Group", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Group
    {
      get { return _Group; }
      set { _Group = value; }
    }
    private int _Mount;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"Mount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Mount
    {
      get { return _Mount; }
      set { _Mount = value; }
    }
    private int _PetID;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"PetID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int PetID
    {
      get { return _PetID; }
      set { _PetID = value; }
    }
    private int _Relic;
    [global::ProtoBuf.ProtoMember(15, IsRequired = true, Name=@"Relic", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Relic
    {
      get { return _Relic; }
      set { _Relic = value; }
    }
    private int _Guild;
    [global::ProtoBuf.ProtoMember(16, IsRequired = true, Name=@"Guild", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Guild
    {
      get { return _Guild; }
      set { _Guild = value; }
    }
    private int _VipLevel;
    [global::ProtoBuf.ProtoMember(17, IsRequired = true, Name=@"VipLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int VipLevel
    {
      get { return _VipLevel; }
      set { _VipLevel = value; }
    }
    private int _VipExp;
    [global::ProtoBuf.ProtoMember(18, IsRequired = true, Name=@"VipExp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int VipExp
    {
      get { return _VipExp; }
      set { _VipExp = value; }
    }
    private int _Partner1;
    [global::ProtoBuf.ProtoMember(19, IsRequired = true, Name=@"Partner1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Partner1
    {
      get { return _Partner1; }
      set { _Partner1 = value; }
    }
    private int _Partner2;
    [global::ProtoBuf.ProtoMember(20, IsRequired = true, Name=@"Partner2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Partner2
    {
      get { return _Partner2; }
      set { _Partner2 = value; }
    }
    private int _CurExp;
    [global::ProtoBuf.ProtoMember(21, IsRequired = true, Name=@"CurExp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int CurExp
    {
      get { return _CurExp; }
      set { _CurExp = value; }
    }
    private readonly global::System.Collections.Generic.List<Protocol.XGem> _Gems = new global::System.Collections.Generic.List<Protocol.XGem>();
    [global::ProtoBuf.ProtoMember(22, Name=@"Gems", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Protocol.XGem> Gems
    {
      get { return _Gems; }
    }
  
    private readonly global::System.Collections.Generic.List<Protocol.XEquip> _Equips = new global::System.Collections.Generic.List<Protocol.XEquip>();
    [global::ProtoBuf.ProtoMember(23, Name=@"Equips", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Protocol.XEquip> Equips
    {
      get { return _Equips; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _CurrAttr = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(24, Name=@"CurrAttr", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> CurrAttr
    {
      get { return _CurrAttr; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _BaseAttr = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(25, Name=@"BaseAttr", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> BaseAttr
    {
      get { return _BaseAttr; }
    }
  
    private Protocol.XTransform _AOI = null;
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"AOI", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Protocol.XTransform AOI
    {
      get { return _AOI; }
      set { _AOI = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"XEffect")]
  public partial class XEffect : global::ProtoBuf.IExtensible
  {
    public XEffect() {}
    
    private int _Id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private Protocol.XTransform _AOI;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"AOI", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Protocol.XTransform AOI
    {
      get { return _AOI; }
      set { _AOI = value; }
    }
    private float _LastTime;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"LastTime", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float LastTime
    {
      get { return _LastTime; }
      set { _LastTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}