//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: MessagePlayer.proto
// Note: requires additional types generated from: MessageID.proto
// Note: requires additional types generated from: MessageRetCode.proto
// Note: requires additional types generated from: MessageCommon.proto
namespace Protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqAddPlayerExp")]
  public partial class ReqAddPlayerExp : global::ProtoBuf.IExtensible
  {
    public ReqAddPlayerExp() {}
    
    private int _Exp;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Exp
    {
      get { return _Exp; }
      set { _Exp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AckAddPlayerExp")]
  public partial class AckAddPlayerExp : global::ProtoBuf.IExtensible
  {
    public AckAddPlayerExp() {}
    
    private int _Exp;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Exp
    {
      get { return _Exp; }
      set { _Exp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}