//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: MessageLogin.proto
// Note: requires additional types generated from: MessageID.proto
// Note: requires additional types generated from: MessageRetCode.proto
// Note: requires additional types generated from: MessageCommon.proto
namespace Protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqLogin")]
  public partial class ReqLogin : global::ProtoBuf.IExtensible
  {
    public ReqLogin() {}
    
    private string _Username;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Username
    {
      get { return _Username; }
      set { _Username = value; }
    }
    private string _Password;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Password
    {
      get { return _Password; }
      set { _Password = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AckLogin")]
  public partial class AckLogin : global::ProtoBuf.IExtensible
  {
    public AckLogin() {}
    
    private string _AuthToken;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"AuthToken", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string AuthToken
    {
      get { return _AuthToken; }
      set { _AuthToken = value; }
    }
    private Protocol.XServer _GameServer;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"GameServer", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Protocol.XServer GameServer
    {
      get { return _GameServer; }
      set { _GameServer = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqRegister")]
  public partial class ReqRegister : global::ProtoBuf.IExtensible
  {
    public ReqRegister() {}
    
    private string _Username;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Username
    {
      get { return _Username; }
      set { _Username = value; }
    }
    private string _Password;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Password
    {
      get { return _Password; }
      set { _Password = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AckRegister")]
  public partial class AckRegister : global::ProtoBuf.IExtensible
  {
    public AckRegister() {}
    
    private string _Username;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Username
    {
      get { return _Username; }
      set { _Username = value; }
    }
    private string _Password;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Password
    {
      get { return _Password; }
      set { _Password = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqLoginGame")]
  public partial class ReqLoginGame : global::ProtoBuf.IExtensible
  {
    public ReqLoginGame() {}
    
    private int _ServerID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ServerID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ServerID
    {
      get { return _ServerID; }
      set { _ServerID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AckLoginGame")]
  public partial class AckLoginGame : global::ProtoBuf.IExtensible
  {
    public AckLoginGame() {}
    
    private readonly global::System.Collections.Generic.List<Protocol.XCharacter> _Players = new global::System.Collections.Generic.List<Protocol.XCharacter>();
    [global::ProtoBuf.ProtoMember(1, Name=@"Players", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Protocol.XCharacter> Players
    {
      get { return _Players; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqGetServers")]
  public partial class ReqGetServers : global::ProtoBuf.IExtensible
  {
    public ReqGetServers() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AckGetServers")]
  public partial class AckGetServers : global::ProtoBuf.IExtensible
  {
    public AckGetServers() {}
    
    private readonly global::System.Collections.Generic.List<Protocol.XServer> _Servers = new global::System.Collections.Generic.List<Protocol.XServer>();
    [global::ProtoBuf.ProtoMember(1, Name=@"Servers", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Protocol.XServer> Servers
    {
      get { return _Servers; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqEnterGame")]
  public partial class ReqEnterGame : global::ProtoBuf.IExtensible
  {
    public ReqEnterGame() {}
    
    private int _RoleID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"RoleID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int RoleID
    {
      get { return _RoleID; }
      set { _RoleID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AckEnterGame")]
  public partial class AckEnterGame : global::ProtoBuf.IExtensible
  {
    public AckEnterGame() {}
    
    private Protocol.XCharacter _Player;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Protocol.XCharacter Player
    {
      get { return _Player; }
      set { _Player = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqCreateRole")]
  public partial class ReqCreateRole : global::ProtoBuf.IExtensible
  {
    public ReqCreateRole() {}
    
    private string _Name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private int _ID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AckCreateRole")]
  public partial class AckCreateRole : global::ProtoBuf.IExtensible
  {
    public AckCreateRole() {}
    
    private Protocol.XCharacter _Player;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Protocol.XCharacter Player
    {
      get { return _Player; }
      set { _Player = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}