-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('Common_pb')


local ERRORMESSAGE = protobuf.Descriptor();
local ERRORMESSAGE_ERRORCODE_FIELD = protobuf.FieldDescriptor();

ERRORMESSAGE_ERRORCODE_FIELD.name = "errorCode"
ERRORMESSAGE_ERRORCODE_FIELD.full_name = ".ErrorMessage.errorCode"
ERRORMESSAGE_ERRORCODE_FIELD.number = 1
ERRORMESSAGE_ERRORCODE_FIELD.index = 0
ERRORMESSAGE_ERRORCODE_FIELD.label = 2
ERRORMESSAGE_ERRORCODE_FIELD.has_default_value = false
ERRORMESSAGE_ERRORCODE_FIELD.default_value = 0
ERRORMESSAGE_ERRORCODE_FIELD.type = 5
ERRORMESSAGE_ERRORCODE_FIELD.cpp_type = 1

ERRORMESSAGE.name = "ErrorMessage"
ERRORMESSAGE.full_name = ".ErrorMessage"
ERRORMESSAGE.nested_types = {}
ERRORMESSAGE.enum_types = {}
ERRORMESSAGE.fields = {ERRORMESSAGE_ERRORCODE_FIELD}
ERRORMESSAGE.is_extendable = false
ERRORMESSAGE.extensions = {}

ErrorMessage = protobuf.Message(ERRORMESSAGE)

