-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('RoomSync_pb')


local GETROOMDATAREQ = protobuf.Descriptor();
local GETROOMDATARESP = protobuf.Descriptor();

GETROOMDATAREQ.name = "GetRoomDataReq"
GETROOMDATAREQ.full_name = ".GetRoomDataReq"
GETROOMDATAREQ.nested_types = {}
GETROOMDATAREQ.enum_types = {}
GETROOMDATAREQ.fields = {}
GETROOMDATAREQ.is_extendable = false
GETROOMDATAREQ.extensions = {}
GETROOMDATARESP.name = "GetRoomDataResp"
GETROOMDATARESP.full_name = ".GetRoomDataResp"
GETROOMDATARESP.nested_types = {}
GETROOMDATARESP.enum_types = {}
GETROOMDATARESP.fields = {}
GETROOMDATARESP.is_extendable = false
GETROOMDATARESP.extensions = {}

GetRoomDataReq = protobuf.Message(GETROOMDATAREQ)
GetRoomDataResp = protobuf.Message(GETROOMDATARESP)

