// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Msg_ID.proto

#ifndef PROTOBUF_Msg_5fID_2eproto__INCLUDED
#define PROTOBUF_Msg_5fID_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)

namespace protobuf_Msg_5fID_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_Msg_5fID_2eproto

enum MessageID {
  MSG_BEGIN = 0,
  MSG_HEART = 1,
  MSG_CONNECT_SUCCESS = 2,
  MSG_DISCONNECT_NTY = 3,
  MSG_LOGINSVR_MSGID_BEGIN = 1000000,
  MSG_CHECK_VERSION_REQ = 1000001,
  MSG_CHECK_VERSION_ACK = 1000002,
  MSG_ACCOUNT_REG_REQ = 1000003,
  MSG_ACCOUNT_REG_ACK = 1000004,
  MSG_ACCOUNT_LOGIN_REQ = 1000005,
  MSG_ACCOUNT_LOGIN_ACK = 1000006,
  MSG_ACCOUNT_LOGINREG_REQ = 1000007,
  MSG_ACCOUNT_LOGINREG_ACK = 1000008,
  MSG_SERVER_LIST_REQ = 1000009,
  MSG_SERVER_LIST_ACK = 1000010,
  MSG_SELECT_SERVER_REQ = 1000011,
  MSG_SELECT_SERVER_ACK = 1000012,
  MSG_LOGIC_REGTO_LOGIN_REQ = 1000013,
  MSG_LOGIC_REGTO_LOGIN_ACK = 1000014,
  MSG_LOGINSVR_MSGID_END = 1999999,
  MSG_LOGICSVR_MSGID_BEGIN = 2000000,
  MSG_ROLE_LIST_REQ = 2000001,
  MSG_ROLE_LIST_ACK = 2000002,
  MSG_ROLE_CREATE_REQ = 2000003,
  MSG_ROLE_CREATE_ACK = 2000004,
  MSG_ROLE_DELETE_REQ = 2000005,
  MSG_ROLE_DELETE_ACK = 2000006,
  MSG_ROLE_LOGIN_REQ = 2000007,
  MSG_ROLE_LOGIN_ACK = 2000008,
  MSG_ROLE_LOGOUT_REQ = 2000009,
  MSG_ROLE_LOGOUT_ACK = 2000010,
  MSG_DATA_UPDATE = 2000011,
  MSG_GAME_REG_LOGIC_REQ = 2000012,
  MSG_GAME_REG_LOGIC_ACK = 2000013,
  MSG_LOGICSVR_MSGID_END = 2999999,
  MSG_SCENESVR_MSGID_BEGIN = 3000000,
  MSG_CREATE_SCENE_REQ = 3000001,
  MSG_CREATE_SCENE_ACK = 3000002,
  MSG_DELETE_SCENE_REQ = 3000003,
  MSG_DELETE_SCENE_ACK = 3000004,
  MSG_SCENE_DESTROY_REQ = 3000005,
  MSG_SCENE_DESTROY_ACK = 3000006,
  MSG_TRANS_ROLE_DATA_REQ = 3000007,
  MSG_TRANS_ROLE_DATA_ACK = 3000008,
  MSG_NOTIFY_ROLE_ENTER_REQ = 3000009,
  MSG_NOTIFY_ROLE_ENTER_ACK = 3000010,
  MSG_ROLE_ENTER_SCENE_REQ = 3000011,
  MSG_ROLE_ENTER_SCENE_ACK = 3000012,
  MSG_OTHER_ENTER_SCENE_REQ = 3000013,
  MSG_OTHER_ENTER_SCENE_ACK = 3000014,
  MSG_ROLE_LEAVE_SCENE_REQ = 3000015,
  MSG_ROLE_LEAVE_SCENE_ACK = 3000016,
  MSG_OTHER_LEAVE_SCENE_ACK = 3000017,
  MSG_ROLE_ACTION_REQ = 3000018,
  MSG_ROLE_ACTION_ACK = 3000019,
  MSG_ROLE_ATTACK_REQ = 3000020,
  MSG_ROLE_ATTACK_ACK = 3000021,
  MSG_SCENESVR_MSGID_END = 3999999,
  MessageID_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  MessageID_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool MessageID_IsValid(int value);
const MessageID MessageID_MIN = MSG_BEGIN;
const MessageID MessageID_MAX = MSG_SCENESVR_MSGID_END;
const int MessageID_ARRAYSIZE = MessageID_MAX + 1;

const ::google::protobuf::EnumDescriptor* MessageID_descriptor();
inline const ::std::string& MessageID_Name(MessageID value) {
  return ::google::protobuf::internal::NameOfEnum(
    MessageID_descriptor(), value);
}
inline bool MessageID_Parse(
    const ::std::string& name, MessageID* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MessageID>(
    MessageID_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::MessageID> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::MessageID>() {
  return ::MessageID_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Msg_5fID_2eproto__INCLUDED
