//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto_raw/Msg_ID.proto
namespace proto_raw.Msg_ID
{
    [global::ProtoBuf.ProtoContract(Name=@"MessageID")]
    public enum MessageID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_BEGIN", Value=0)]
      MSG_BEGIN = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_HEART", Value=1)]
      MSG_HEART = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_CONNECT_SUCCESS", Value=2)]
      MSG_CONNECT_SUCCESS = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_CONNECT_FAIL", Value=3)]
      MSG_CONNECT_FAIL = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_DISCONNECT", Value=4)]
      MSG_DISCONNECT = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_LOGINSVR_MSGID_BEGIN", Value=1000000)]
      MSG_LOGINSVR_MSGID_BEGIN = 1000000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_CHECK_VERSION_REQ", Value=1000001)]
      MSG_CHECK_VERSION_REQ = 1000001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_CHECK_VERSION_ACK", Value=1000002)]
      MSG_CHECK_VERSION_ACK = 1000002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_ACCOUNT_REG_REQ", Value=1000003)]
      MSG_ACCOUNT_REG_REQ = 1000003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_ACCOUNT_REG_ACK", Value=1000004)]
      MSG_ACCOUNT_REG_ACK = 1000004,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_ACCOUNT_LOGIN_REQ", Value=1000005)]
      MSG_ACCOUNT_LOGIN_REQ = 1000005,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_ACCOUNT_LOGIN_ACK", Value=1000006)]
      MSG_ACCOUNT_LOGIN_ACK = 1000006,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_SERVER_LIST_REQ", Value=1000007)]
      MSG_SERVER_LIST_REQ = 1000007,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_SERVER_LIST_ACK", Value=1000008)]
      MSG_SERVER_LIST_ACK = 1000008,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_SELECT_SERVER_REQ", Value=1000009)]
      MSG_SELECT_SERVER_REQ = 1000009,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_SELECT_SERVER_ACK", Value=1000010)]
      MSG_SELECT_SERVER_ACK = 1000010,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_LOGIC_REGTO_LOGIN_REQ", Value=1000011)]
      MSG_LOGIC_REGTO_LOGIN_REQ = 1000011,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_LOGIC_REGTO_LOGIN_ACK", Value=1000012)]
      MSG_LOGIC_REGTO_LOGIN_ACK = 1000012,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_GAMESVR_MSGID_BEGIN", Value=2000000)]
      MSG_GAMESVR_MSGID_BEGIN = 2000000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_ROLE_LIST_REQ", Value=2000001)]
      MSG_ROLE_LIST_REQ = 2000001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_ROLE_LIST_ACK", Value=2000002)]
      MSG_ROLE_LIST_ACK = 2000002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_ROLE_CREATE_REQ", Value=2000003)]
      MSG_ROLE_CREATE_REQ = 2000003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_ROLE_CREATE_ACK", Value=2000004)]
      MSG_ROLE_CREATE_ACK = 2000004,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_ROLE_DELETE_REQ", Value=2000005)]
      MSG_ROLE_DELETE_REQ = 2000005,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_ROLE_DELETE_ACK", Value=2000006)]
      MSG_ROLE_DELETE_ACK = 2000006,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_ROLE_LOGIN_REQ", Value=2000007)]
      MSG_ROLE_LOGIN_REQ = 2000007,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_ROLE_LOGIN_ACK", Value=2000008)]
      MSG_ROLE_LOGIN_ACK = 2000008,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_ROLE_LOGOUT_REQ", Value=2000009)]
      MSG_ROLE_LOGOUT_REQ = 2000009,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_ROLE_LOGOUT_ACK", Value=2000010)]
      MSG_ROLE_LOGOUT_ACK = 2000010,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_DATA_UPDATE", Value=2000011)]
      MSG_DATA_UPDATE = 2000011,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_SCENESVR_MSGID_BEGIN", Value=3000000)]
      MSG_SCENESVR_MSGID_BEGIN = 3000000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_CAN_ENTER_HOME_SCENE", Value=3000001)]
      MSG_CAN_ENTER_HOME_SCENE = 3000001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_ENTER_HOME_SCENE_REQ", Value=3000002)]
      MSG_ENTER_HOME_SCENE_REQ = 3000002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_ENTER_HOME_SCENE_ACK", Value=3000003)]
      MSG_ENTER_HOME_SCENE_ACK = 3000003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_ENTER_HOME_SCENE_NTY", Value=3000004)]
      MSG_ENTER_HOME_SCENE_NTY = 3000004,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_LEAVE_HOME_SCENE_REQ", Value=3000005)]
      MSG_LEAVE_HOME_SCENE_REQ = 3000005,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_LEAVE_HOME_SCENE_ACK", Value=3000006)]
      MSG_LEAVE_HOME_SCENE_ACK = 3000006,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_LEAVE_HOME_SCENE_NTY", Value=3000007)]
      MSG_LEAVE_HOME_SCENE_NTY = 3000007,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_COPYSVR_MSGID_BEGIN", Value=4000000)]
      MSG_COPYSVR_MSGID_BEGIN = 4000000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_CAN_ENTER_COPY", Value=4000001)]
      MSG_CAN_ENTER_COPY = 4000001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_ENTER_COPY_REQ", Value=4000002)]
      MSG_ENTER_COPY_REQ = 4000002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_ENTER_COPY_ACK", Value=4000003)]
      MSG_ENTER_COPY_ACK = 4000003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_ENTER_COPY_NTY", Value=4000004)]
      MSG_ENTER_COPY_NTY = 4000004,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_LEAVE_COPY_REQ", Value=4000005)]
      MSG_LEAVE_COPY_REQ = 4000005,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_LEAVE_COPY_ACK", Value=4000006)]
      MSG_LEAVE_COPY_ACK = 4000006,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_LEAVE_COPY_NTY", Value=4000007)]
      MSG_LEAVE_COPY_NTY = 4000007,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_ROLE_ACTION_REQ", Value=4000008)]
      MSG_ROLE_ACTION_REQ = 4000008,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_ROLE_ACTION_ACK", Value=4000009)]
      MSG_ROLE_ACTION_ACK = 4000009,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_ROLE_ACTION_NTY", Value=4000010)]
      MSG_ROLE_ACTION_NTY = 4000010,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_ROLE_ATTACK_REQ", Value=4000011)]
      MSG_ROLE_ATTACK_REQ = 4000011,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_ROLE_ATTACK_ACK", Value=4000012)]
      MSG_ROLE_ATTACK_ACK = 4000012
    }
  
}
// Generated from: proto_raw/Msg_Login.proto
namespace proto_raw.Msg_Login
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CheckVersionReq")]
  public partial class CheckVersionReq : global::ProtoBuf.IExtensible
  {
    public CheckVersionReq() {}
    
    private int _ClientVerion = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ClientVerion", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ClientVerion
    {
      get { return _ClientVerion; }
      set { _ClientVerion = value; }
    }
    private string _PackageName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"PackageName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string PackageName
    {
      get { return _PackageName; }
      set { _PackageName = value; }
    }
    private string _Channel = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Channel", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Channel
    {
      get { return _Channel; }
      set { _Channel = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CheckVersionAck")]
  public partial class CheckVersionAck : global::ProtoBuf.IExtensible
  {
    public CheckVersionAck() {}
    
    private int _RetCode = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"RetCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int RetCode
    {
      get { return _RetCode; }
      set { _RetCode = value; }
    }
    private int _ClientVerion = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"ClientVerion", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ClientVerion
    {
      get { return _ClientVerion; }
      set { _ClientVerion = value; }
    }
    private string _PackageName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"PackageName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string PackageName
    {
      get { return _PackageName; }
      set { _PackageName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AccountRegReq")]
  public partial class AccountRegReq : global::ProtoBuf.IExtensible
  {
    public AccountRegReq() {}
    
    private string _AccountName = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"AccountName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string AccountName
    {
      get { return _AccountName; }
      set { _AccountName = value; }
    }
    private string _Password = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Password
    {
      get { return _Password; }
      set { _Password = value; }
    }
    private string _Channel = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Channel", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Channel
    {
      get { return _Channel; }
      set { _Channel = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AccountRegAck")]
  public partial class AccountRegAck : global::ProtoBuf.IExtensible
  {
    public AccountRegAck() {}
    
    private int _RetCode = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"RetCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int RetCode
    {
      get { return _RetCode; }
      set { _RetCode = value; }
    }
    private long _AccountID = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"AccountID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long AccountID
    {
      get { return _AccountID; }
      set { _AccountID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AccountLoginReq")]
  public partial class AccountLoginReq : global::ProtoBuf.IExtensible
  {
    public AccountLoginReq() {}
    
    private string _AccountName = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"AccountName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string AccountName
    {
      get { return _AccountName; }
      set { _AccountName = value; }
    }
    private string _Password = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Password
    {
      get { return _Password; }
      set { _Password = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AccountLoginAck")]
  public partial class AccountLoginAck : global::ProtoBuf.IExtensible
  {
    public AccountLoginAck() {}
    
    private int _RetCode = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"RetCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int RetCode
    {
      get { return _RetCode; }
      set { _RetCode = value; }
    }
    private long _AccountID = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"AccountID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long AccountID
    {
      get { return _AccountID; }
      set { _AccountID = value; }
    }
    private int _LastSvrID = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"LastSvrID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int LastSvrID
    {
      get { return _LastSvrID; }
      set { _LastSvrID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ClientServerListReq")]
  public partial class ClientServerListReq : global::ProtoBuf.IExtensible
  {
    public ClientServerListReq() {}
    
    private long _AccountID = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"AccountID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long AccountID
    {
      get { return _AccountID; }
      set { _AccountID = value; }
    }
    private string _Channel = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Channel", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Channel
    {
      get { return _Channel; }
      set { _Channel = value; }
    }
    private string _PackName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"PackName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string PackName
    {
      get { return _PackName; }
      set { _PackName = value; }
    }
    private int _ClientVersion = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"ClientVersion", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ClientVersion
    {
      get { return _ClientVersion; }
      set { _ClientVersion = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ClientServerNode")]
  public partial class ClientServerNode : global::ProtoBuf.IExtensible
  {
    public ClientServerNode() {}
    
    private int _SvrID = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"SvrID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int SvrID
    {
      get { return _SvrID; }
      set { _SvrID = value; }
    }
    private string _SvrName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"SvrName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string SvrName
    {
      get { return _SvrName; }
      set { _SvrName = value; }
    }
    private uint _SvrState = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"SvrState", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint SvrState
    {
      get { return _SvrState; }
      set { _SvrState = value; }
    }
    private uint _SvrDefault = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"SvrDefault", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint SvrDefault
    {
      get { return _SvrDefault; }
      set { _SvrDefault = value; }
    }
    private int _SvrOpenTime = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"SvrOpenTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int SvrOpenTime
    {
      get { return _SvrOpenTime; }
      set { _SvrOpenTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ClientServerListAck")]
  public partial class ClientServerListAck : global::ProtoBuf.IExtensible
  {
    public ClientServerListAck() {}
    
    private int _RetCode = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"RetCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int RetCode
    {
      get { return _RetCode; }
      set { _RetCode = value; }
    }
    private readonly global::System.Collections.Generic.List<ClientServerNode> _SvrNode = new global::System.Collections.Generic.List<ClientServerNode>();
    [global::ProtoBuf.ProtoMember(2, Name=@"SvrNode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ClientServerNode> SvrNode
    {
      get { return _SvrNode; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RegToLoginSvrReq")]
  public partial class RegToLoginSvrReq : global::ProtoBuf.IExtensible
  {
    public RegToLoginSvrReq() {}
    
    private int _ServerID = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ServerID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ServerID
    {
      get { return _ServerID; }
      set { _ServerID = value; }
    }
    private string _ServerName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"ServerName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ServerName
    {
      get { return _ServerName; }
      set { _ServerName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RegToLoginSvrAck")]
  public partial class RegToLoginSvrAck : global::ProtoBuf.IExtensible
  {
    public RegToLoginSvrAck() {}
    
    private int _RetCode = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"RetCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int RetCode
    {
      get { return _RetCode; }
      set { _RetCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SelectServerReq")]
  public partial class SelectServerReq : global::ProtoBuf.IExtensible
  {
    public SelectServerReq() {}
    
    private int _ServerID = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ServerID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ServerID
    {
      get { return _ServerID; }
      set { _ServerID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SelectServerAck")]
  public partial class SelectServerAck : global::ProtoBuf.IExtensible
  {
    public SelectServerAck() {}
    
    private int _RetCode = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"RetCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int RetCode
    {
      get { return _RetCode; }
      set { _RetCode = value; }
    }
    private string _ServerAddr = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"ServerAddr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ServerAddr
    {
      get { return _ServerAddr; }
      set { _ServerAddr = value; }
    }
    private int _ServerPort = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"ServerPort", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ServerPort
    {
      get { return _ServerPort; }
      set { _ServerPort = value; }
    }
    private int _LoginCode = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"LoginCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int LoginCode
    {
      get { return _LoginCode; }
      set { _LoginCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoleListNode")]
  public partial class RoleListNode : global::ProtoBuf.IExtensible
  {
    public RoleListNode() {}
    
    private int _SvrID = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"SvrID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int SvrID
    {
      get { return _SvrID; }
      set { _SvrID = value; }
    }
    private string _SvrName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"SvrName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string SvrName
    {
      get { return _SvrName; }
      set { _SvrName = value; }
    }
    private uint _SvrState = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"SvrState", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint SvrState
    {
      get { return _SvrState; }
      set { _SvrState = value; }
    }
    private uint _SvrDefault = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"SvrDefault", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint SvrDefault
    {
      get { return _SvrDefault; }
      set { _SvrDefault = value; }
    }
    private int _SvrOpenTime = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"SvrOpenTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int SvrOpenTime
    {
      get { return _SvrOpenTime; }
      set { _SvrOpenTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoleListReq")]
  public partial class RoleListReq : global::ProtoBuf.IExtensible
  {
    public RoleListReq() {}
    
    private int _LoginCode = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"LoginCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int LoginCode
    {
      get { return _LoginCode; }
      set { _LoginCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoleListAck")]
  public partial class RoleListAck : global::ProtoBuf.IExtensible
  {
    public RoleListAck() {}
    
    private int _RetCode = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"RetCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int RetCode
    {
      get { return _RetCode; }
      set { _RetCode = value; }
    }
    private readonly global::System.Collections.Generic.List<RoleListNode> _RoleNode = new global::System.Collections.Generic.List<RoleListNode>();
    [global::ProtoBuf.ProtoMember(2, Name=@"RoleNode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<RoleListNode> RoleNode
    {
      get { return _RoleNode; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoleLoginReq")]
  public partial class RoleLoginReq : global::ProtoBuf.IExtensible
  {
    public RoleLoginReq() {}
    
    private long _AccountID = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"AccountID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long AccountID
    {
      get { return _AccountID; }
      set { _AccountID = value; }
    }
    private long _LoginCode = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"LoginCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long LoginCode
    {
      get { return _LoginCode; }
      set { _LoginCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoleLoginAck")]
  public partial class RoleLoginAck : global::ProtoBuf.IExtensible
  {
    public RoleLoginAck() {}
    
    private int _RetCode = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"RetCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int RetCode
    {
      get { return _RetCode; }
      set { _RetCode = value; }
    }
    private long _AccountID = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"AccountID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long AccountID
    {
      get { return _AccountID; }
      set { _AccountID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnterSceneDataReq")]
  public partial class EnterSceneDataReq : global::ProtoBuf.IExtensible
  {
    public EnterSceneDataReq() {}
    
    private long _RoleID = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"RoleID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long RoleID
    {
      get { return _RoleID; }
      set { _RoleID = value; }
    }
    private string _RoleName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"RoleName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string RoleName
    {
      get { return _RoleName; }
      set { _RoleName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnterSceneDataAck")]
  public partial class EnterSceneDataAck : global::ProtoBuf.IExtensible
  {
    public EnterSceneDataAck() {}
    
    private int _RetCode = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"RetCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int RetCode
    {
      get { return _RetCode; }
      set { _RetCode = value; }
    }
    private long _AccountID = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"AccountID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long AccountID
    {
      get { return _AccountID; }
      set { _AccountID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnterCopyDataReq")]
  public partial class EnterCopyDataReq : global::ProtoBuf.IExtensible
  {
    public EnterCopyDataReq() {}
    
    private long _RoleID = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"RoleID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long RoleID
    {
      get { return _RoleID; }
      set { _RoleID = value; }
    }
    private string _RoleName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"RoleName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string RoleName
    {
      get { return _RoleName; }
      set { _RoleName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnterCopyDataAck")]
  public partial class EnterCopyDataAck : global::ProtoBuf.IExtensible
  {
    public EnterCopyDataAck() {}
    
    private int _RetCode = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"RetCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int RetCode
    {
      get { return _RetCode; }
      set { _RetCode = value; }
    }
    private long _AccountID = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"AccountID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long AccountID
    {
      get { return _AccountID; }
      set { _AccountID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}